### ISSUE TITLE
MongoDB database not found after setting up MongoBI

### ISSUE THREAD

**Issue by pixar634** [cube-js/cube#1587]
```
CUBEJS_DB_HOST=<the host as mentioned on atlas>
CUBEJS_DB_NAME=hyper-staging
CUBEJS_DB_USER=<name>?source=admin
CUBEJS_DB_PASS=<pass>
CUBEJS_DB_PORT=<port>
CUBEJS_WEB_SOCKETS=true
CUBEJS_DEV_MODE=true
CUBEJS_DB_TYPE=mongobi
CUBEJS_API_SECRET=secret
CUBEJS_DB_SSL=true
#CUBEJS_DB_SSL_CA=<SSL_CA>
#CUBEJS_DB_SSL_CERT=<SSL_CERT>
#CUBEJS_DB_SSL_CIPHERS=<SSL_CIPHERS>
#CUBEJS_DB_SSL_PASSPHRASE=<SSL_PASSPHRASE>
#CUBEJS_DB_SSL_REJECT_UNAUTHORIZED=<SSL_REJECT_UNAUTHORIZED>
```

```
Error: error using database hyper-staging: ERROR 1049 (42000): Unknown database 'hyper-staging' 
at Packet.asError (C:\personal project\hello-world\node_modules\mysql2\lib\packets\packet.js:712:17) 
at ClientHandshake.execute (C:\personal project\hello-world\node_modules\mysql2\lib\commands\command.js:28:26) 
at Connection.handlePacket (C:\personal project\hello-world\node_modules\mysql2\lib\connection.js:425:32) 
at PacketParser.onPacket (C:\personal project\hello-world\node_modules\mysql2\lib\connection.js:75:12) 
at PacketParser.executeStart (C:\personal project\hello-world\node_modules\mysql2\lib\packet_parser.js:75:16) 
at TLSSocket.<anonymous> (C:\personal project\hello-world\node_modules\mysql2\lib\connection.js:345:25) 
at TLSSocket.emit (events.js:315:20) 
at addChunk (_stream_readable.js:295:12) 
at readableAddChunk (_stream_readable.js:271:9) 
at TLSSocket.Readable.push (_stream_readable.js:212:10)
```

That database exists in my cluster  , yet shows this error. Help!

**Comment by hassankhan** [comment]
Hi @pixar634 👋 

Have you already run `mongoimport`?  If not, you can find an example under 'Importing test dataset' in our ['Building MongoDB Dashboard using Node.js'](https://cube.dev/blog/building-mongodb-dashboard-using-node.js) blog post. Hope that helps 👍

**Comment by pixar634** [comment]
@hassankhan that blog is for localhost setup i think, my database is in atlas, and I'm trying to connect with it, The database is also there, but its showing, the database doesn't exist.

**Comment by dlariosuniandes** [comment]
Did you find any solutions?

**Comment by schoolytics-cto** [comment]
Trying to setup mongoBI running on atlas, keep getting
```
Error: connect ETIMEDOUT
    at Connection._handleTimeoutError (/Users/philips/Developer/cubejs/cubejs-docker/node_modules/mysql2/lib/connection.js:178:17)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
```

**Comment by igorlukanin** [comment]
Please feel free to reopen this one if it's still relevant.
