### ISSUE TITLE
There is some  bug  for define cube schema with `COMPILE_CONTEXT`  or `SECURITY_CONTEXT` ?

### ISSUE THREAD

**Issue by rongfengliang** [cube-js/cube#1958]
**Describe the bug**

from code i know  compilerApi will be cache if running  we with  preAggregation  
when i   call with http request nill not recompile  so  some defined variables will be  undefined 
and generate sql query will be  wrong though i provide right `COMPILE_CONTEXT` information   from jwt token

**Version:**
[e.g. 0.26.0]

**Comment by ovr** [comment]
@rongfengliang Can you try with `v0.26.1`? Does it work?

Thanks

**Comment by rongfengliang** [comment]
> @rongfengliang Can you try with `v0.26.1`? Does it work?
> 
> Thanks


i mean like this 

```code


const { securityContext: { total_amount } } = COMPILE_CONTEXT;

const filter_count = total_amount

cube(`demoapp`, {
    sql: ` SELECT
    *
FROM 
    transactions AS ts
    where  total_amount  > ${filter_count}
`,
    measures: {
        average_spend_per_customer: {
            sql: `${sum}/${count}`,
            type: `number`
        },
        count: {
            sql: `total_amount`,
            type: `count`,
        },
        sum: {
            sql: `total_amount`,
            type: `sum`,
        }
    },
    dimensions: {
        total_amount: {
            sql: `total_amount`,
            type: `number`
        },
        customer_id: {
            sql: `customer_id`,
            type: `string`
        },
        transaction_date: {
            sql: `transaction_date`,
            type: `time`,
            shown: false
        },
        event_id: {
            sql: `event_id`,
            type: `string`
        }
    }
});

```

beacause  user don't do some request `COMPILE_CONTEXT `'s  total_amount  will  be null (cube.js internal has some scheduler task) but when i pass jwt token with 
total_amount it  dons't work beacause compileapi is cached 

error message

```code
TypeError: Cannot destructure property `total_amount` of 'undefined' or 'null'.
    at app.js:2:20
    at Script.runInContext (vm.js:127:20)
    at Script.runInNewContext (vm.js:133:17)
    at Object.runInNewContext (vm.js:299:38)
    at DataSchemaCompiler.compileFile (/Users/dalong/mylearning/cube-app-demo/hello-world/node_modules/@cubejs-backend/schema-compiler/src/compiler/DataSchemaCompiler.js:170:10)
    at /Users/dalong/mylearning/cube-app-demo/hello-world/node_modules/@cubejs-backend/schema-compiler/src/compiler/DataSchemaCompiler.js:135:14
    at Array.forEach (<anonymous>)
    at DataSchemaCompiler.compileCubeFiles (/Users/dalong/mylearning/cube-app-demo/hello-world/node_modules/@cubejs-backend/schema-compiler/src/compiler/DataSchemaCompiler.js:134:8)
    at compilePhase (/Users/dalong/mylearning/cube-app-demo/hello-world/node_modules/@cubejs-backend/schema-compiler/src/compiler/DataSchemaCompiler.js:60:50)
    at /Users/dalong/mylearning/cube-app-demo/hello-world/node_modules/@cubejs-backend/schema-compiler/src/compiler/DataSchemaCompiler.js:64:23
    at ErrorReporter.throwIfAny (/Users/dalong/mylearning/cube-app-demo/hello-world/node_modules/@cubejs-backend/schema-compiler/src/compiler/ErrorReporter.ts:127:13)
```

**Comment by igorlukanin** [comment]
`scheduledRefreshContexts` option should be used to provide necessary `COMPILE_CONTEXT`s at the time of data model compilation: https://cube.dev/docs/reference/configuration/config#scheduledrefreshcontexts
