### ISSUE TITLE
In MySQL driver, freeing a connection wouldn't work after a query timeout

### ISSUE THREAD

**Issue by igorlukanin** [cube-js/cube#2973]
**Describe the bug**
See Slack for context: https://cube-js.slack.com/archives/CC0403RRR/p1623942326412600?thread_ts=1623766932.341900&cid=CC0403RRR

```
cube_1       | Database Pool Error: undefined
cube_1       | {}
cube_1       | Error: Cannot enqueue Query after fatal error.
cube_1       |     at Protocol._validateEnqueue (/cube/node_modules/mysql/lib/protocol/Protocol.js:212:16)
cube_1       |     at Protocol._enqueue (/cube/node_modules/mysql/lib/protocol/Protocol.js:138:13)
cube_1       |     at Connection.query (/cube/node_modules/mysql/lib/Connection.js:198:25)
cube_1       |     at internal/util.js:297:30
cube_1       |     at new Promise (<anonymous>)
cube_1       |     at Connection.bound query [as execute] (internal/util.js:296:12)
```

**Comment by igorlukanin** [comment]
Closing since there are not enough details to reproduce and the Slack thread has already expired.
