### ISSUE TITLE
PreAggregation for sql containing CTE/with generating sql sytnax error

### ISSUE THREAD

**Issue by joshhubers** [cube-js/cube#3270]
**Describe the bug**
I have recently upgraded:
Cube Server version from: 0.27.53  to 0.28.22
Big query driver from 0.27.53 to 0.28.22

I'm seeing a "Error: Syntax error: Unexpected keyword SELECT at [{line}:{col}]" for a handful of cubes that I have defined that utilze CTE's / with in the sql definition with a pre-aggregate defined. When I comment out the pre-aggregate I no longer get the syntax error

**To Reproduce**
1. Define a cube utilizing a "WITH" statement
2. Define a pre-aggregate utilizing this cube

**Expected behavior**
I would expect the query to execute as expected and the data to be accurately pre-aggregated

**Screenshots**

**Version:**
Server version: 0.28.22
Big query driver: 0.28.22

**Additional context**
Cube looks like the following:

```
cube('UniqueAttenders', {
  dataSource: `${cubejsBillingProject()}`,

  sqlAlias: 'u_att',

  sql: `with service_intervals as 
      (
        select *
        from unnest(GENERATE_TIMESTAMP_ARRAY(${FILTER_PARAMS.UniqueAttenders.serviceTime.filter((from, to) =>
          `${from}, ${to}, INTERVAL 5 MINUTE)) as service_interval`)}
      )

      select 
        service_intervals.service_interval,
        count(distinct(concat(sessions.subscriber_id, service_id))) as active_sessions,
        service_id,
        organization_id
      from ${cubejsDataProject()}.fact_sessions sessions
      cross join unnest (sessions.service_ids) as service_id
      inner join service_intervals on sessions.session_end >= service_intervals.service_interval 
        and sessions.session_start <= service_intervals.service_interval
      where ${FILTER_PARAMS.UniqueAttenders.serviceId.filter('service_id')}
        and ${FILTER_PARAMS.UniqueAttenders.organizationId.filter('organization_id')}
      group by 
        service_intervals.service_interval,
        service_id,
        organization_id
    `,

  measures: {
    activeSessions: {
      sql: `${CUBE}.active_sessions`,
      type: 'sum',
    },
    maxActiveSessions: {
      sql: `${CUBE}.active_sessions`,
      type: 'max',
    },
  },

  dimensions: {
    serviceTime: {
      sql: `${CUBE}.service_interval`,
      type: 'time',
    },
    serviceId: {
      sql: `${CUBE}.service_id`,
      type: 'string',
    },
    organizationId: {
      sql: `${CUBE}.organization_id`,
      type: 'string',
    },
  },

  preAggregations: {
    date: {
      type: 'rollup',
      measures: [activeSessions],
      timeDimension: serviceTime,
      dimensions: [organizationId, serviceId],
      granularity: 'minute',
      partitionGranularity: 'hour',
      external: true,
      scheduledRefresh: true,
      refreshKey: {
        every: `15 minute`,
        incremental: true,
	updateWindow: `7 day`
      }
    },
  },
});
```

The generated sql / server logs show the following:
```
Error while querying: scheduler-fdbf3d7a-22aa-4003-b310-2de980a4265a (415ms)
{
  "processingId": "2725",
  "queueSize": 2,
  "queryKey": [
    "select max(DATETIME(`u_att`.service_interval, 'UTC')) from (with service_intervals as \n      (\n        select *\n        from unnest(GENERATE_TIMESTAMP_ARRAY(1 = 1\n      )\n\n      select \n        service_intervals.service_interval,\n        count(distinct(concat(sessions.subscriber_id, service_id))) as active_sessions,\n        service_id,\n        organization_id\n      from fact_sessions sessions\n      cross join unnest (sessions.service_ids) as service_id\n      inner join service_intervals on sessions.session_end >= service_intervals.service_interval \n        and sessions.session_start <= service_intervals.service_interval\n      where 1 = 1\n        and 1 = 1\n      group by \n        service_intervals.service_interval,\n        service_id,\n        organization_id\n    ) AS `u_att`",
    []
  ],
  "queuePrefix": "SQL_QUERY_STANDALONE_default",
  "timeInQueue": 2
}
Error: Syntax error: Unexpected keyword SELECT at [7:7]
    at new ApiError (/Users/joshhubers/Code/project/metrics/node_modules/@google-cloud/common/build/src/util.js:59:15)
    at /Users/joshhubers/Code/project/metrics/node_modules/@cubejs-backend/bigquery-driver/node_modules/@google-cloud/bigquery/build/src/bigquery.js:1221:23
    at /Users/joshhubers/Code/project/metrics/node_modules/@google-cloud/common/build/src/util.js:369:25
    at Util.handleResp (/Users/joshhubers/Code/project/metrics/node_modules/@google-cloud/common/build/src/util.js:145:9)
    at /Users/joshhubers/Code/project/metrics/node_modules/@google-cloud/common/build/src/util.js:434:22
    at onResponse (/Users/joshhubers/Code/project/metrics/node_modules/retry-request/index.js:214:7)
    at /Users/joshhubers/Code/project/metrics/node_modules/teeny-request/src/index.ts:325:11
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    ```

**Comment by ovr** [comment]
Hello @joshhubers,

I think you forget about `,` after `)` for WITH.


```sql
with service_intervals as 
      (
        select *
        from unnest(GENERATE_TIMESTAMP_ARRAY(${FILTER_PARAMS.UniqueAttenders.serviceTime.filter((from, to) =>
          `${from}, ${to}, INTERVAL 5 MINUTE)) as service_interval`)}
      ), # THIS PLACE
```

Thanks

**Comment by joshhubers** [comment]
Thanks for the response @ovr . Unless I'm missing something I know get the following:

```
Error while querying: OGNkOWM0NzAtMWI1Zi00OWE1LTg2YjYtMGY2NTQ1NDhlYzQ4LXNwYW4tMQ (2009ms)
{
  "processingId": "211",
  "queueSize": 5,
  "queryKey": [
    "select max(DATETIME(`u_att`.service_interval, 'America/Detroit')) from (with service_intervals as \n      (\n        select *\n        from unnest(GENERATE_TIMESTAMP_ARRAY(1 = 1\n      ),\n\n      select \n        service_intervals.service_interval,\n        count(distinct(concat(sessions.subscriber_id, service_id))) as active_sessions,\n        service_id,\n        organization_id\n      from life-church-analytics-staging.chop.fact_sessions sessions\n      cross join unnest (sessions.service_ids) as service_id\n      inner join service_intervals on sessions.session_end >= service_intervals.service_interval \n        and sessions.session_start <= service_intervals.service_interval\n      where 1 = 1\n        and 1 = 1\n      group by \n        service_intervals.service_interval,\n        service_id,\n        organization_id\n    ) AS `u_att`",
    []
  ],
  "queuePrefix": "SQL_QUERY_STANDALONE_default",
  "timeInQueue": 58
}
Error: Syntax error: Unexpected "," at [5:8]
    at new ApiError (/Users/joshhubers/Code/lifechurch/metrics/node_modules/@google-cloud/common/build/src/util.js:59:15)
    at /Users/joshhubers/Code/lifechurch/metrics/node_modules/@cubejs-backend/bigquery-driver/node_modules/@google-cloud/bigquery/build/src/bigquery.js:1221:23
    at /Users/joshhubers/Code/lifechurch/metrics/node_modules/@google-cloud/common/build/src/util.js:369:25
    at Util.handleResp (/Users/joshhubers/Code/lifechurch/metrics/node_modules/@google-cloud/common/build/src/util.js:145:9)
    at /Users/joshhubers/Code/lifechurch/metrics/node_modules/@google-cloud/common/build/src/util.js:434:22
    at onResponse (/Users/joshhubers/Code/lifechurch/metrics/node_modules/retry-request/index.js:214:7)
    at /Users/joshhubers/Code/lifechurch/metrics/node_modules/teeny-request/src/index.ts:325:11
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by joshhubers** [comment]
Additionally, when I have the comma present, and comment out the pre-aggregation I get `"Error: Syntax error: Trailing comma after the WITH clause before the SELECT clause is not allowed at [10:7]"`

**Comment by elhe26** [comment]
Hey @joshhubers , did you solve this issue?

**Comment by joshhubers** [comment]
Hi @elhe26 ,

This was quite a long time ago, and unfortunately I don't remember what happened in this scenario and I no longer have access to the code base I was working on that presented that issue. 

I may have gotten around it by re-writing the query to not leverage a CTE, but honestly I can't remember.

Apologies and good luck!
