### ISSUE TITLE
ClickHouse pre-aggregations index construction sql issue

### ISSUE THREAD

**Issue by olejeglejeg** [cube-js/cube#3756]
**Describe the bug**
We are facing a strange issue with Clickhouse cube and their pre-aggregations. Currently, we are working on adding Clickhouse as a second data source to our cube-js self-deployed setup. We already configured ClickhouseDriver and test it with cube which presents at the bottom, and all was fine. But when we started to add pre-aggregations to this cube, we found an issue with index creation for this one, which seems like cube tries to create an index for Сlickhouse tables in a Postgres like manner.

**To Reproduce**
Trace log with error:
```
Error while querying: {"processingId":"157","queueSize":8,"duration":487,"queryKey":[["CREATE TABLE cube.clickstream_product_view_count_by_product_id_and_seller_id20211123 ENGINE = MergeTree() ORDER BY (`clickstream_product_view__product_id`, `clickstream_product_to_seller_dict__seller_id`) AS SELECT\n      `clickstream_product_to_seller_dict`.seller_id `clickstream_product_to_seller_dict__seller_id`, `clickstream_product_view`.product_id `clickstream_product_view__product_id`, toDateTime(toStartOfDay(toTimeZone(toDateTime(`clickstream_product_view`.received_at), 'UTC'), 'UTC'), 'UTC') `clickstream_product_view__received_at_day`, count(`clickstream_product_view`.event_id) `clickstream_product_view__count`\n    FROM\n      (SELECT * FROM kazanexpress.events WHERE event_type = 'PRODUCT_VIEW') AS `clickstream_product_view`\nLEFT JOIN kazanexpress.product_id_to_seller_id AS `clickstream_product_to_seller_dict` ON `clickstream_product_view`.product_id = `clickstream_product_to_seller_dict`.product_id  WHERE (`clickstream_product_view`.received_at >= parseDateTimeBestEffort(?) AND `clickstream_product_view`.received_at <= parseDateTimeBestEffort(?)) GROUP BY `clickstream_product_to_seller_dict__seller_id`, `clickstream_product_view__product_id`, `clickstream_product_view__received_at_day`",["2021-11-23T00:00:00.000Z","2021-11-23T23:59:59.999Z"],{}],[{"indexName":"clickstream_product_view_count_by_product_id_and_seller_id_product_ids_index","sql":["CREATE INDEX clickstream_product_view_count_by_product_id_and_seller_id_product_ids_index ON cube.clickstream_product_view_count_by_product_id_and_seller_id20211123 (`clickstream_product_view__product_id`, `clickstream_product_to_seller_dict__seller_id`)",[],{}]}],[[{"refresh_key":null}]]],"queuePrefix":"SQL_PRE_AGGREGATIONS_STANDALONE_clickhouse","requestId":"43a84184395c018466c273359bc08c2c","timeInQueue":46,"preAggregationId":"ClickstreamProductView.countByProductIdAndSellerId","newVersionEntry":{"table_name":"cube.clickstream_product_view_count_by_product_id_and_seller_id20211123","structure_version":"o3rgpzm4","content_version":"ylerwbqv","last_updated_at":1638194524844,"naming_version":2},"error":"Error: Error during create table: CREATE TABLE cube.clickstream_product_view_count_by_product_id_and_seller_id20211123_ylerwbqv_o3rgpzm4_1gq9nas (`clickstream_product_to_seller_dict__seller_id` Nullable(UInt64), `clickstream_product_view__product_id` bigint, `clickstream_product_view__received_at_day` timestamp, `clickstream_product_view__count` bigint) INDEX clickstream_product_view_count_by_product_id_and_seller_id_product_ids_index_ylerwbqv_o3rgpzm4_1gq9nas (`clickstream_product_view__product_id`, `clickstream_product_to_seller_dict__seller_id`) LOCATION ?: Internal: ParserError(\"Expected ',' or ')' after column definition, found: (\")\n    at WebSocket.<anonymous> (/cube/node_modules/@cubejs-backend/cubestore-driver/src/WebSocketConnection.ts:87:30)\n    at WebSocket.emit (events.js:314:20)\n    at Receiver.receiverOnMessage (/cube/node_modules/ws/lib/websocket.js:1008:20)\n    at Receiver.emit (events.js:314:20)\n    at Receiver.dataMessage (/cube/node_modules/ws/lib/receiver.js:502:14)\n    at Receiver.getData (/cube/node_modules/ws/lib/receiver.js:435:17)\n    at Receiver.startLoop (/cube/node_modules/ws/lib/receiver.js:143:22)\n    at Receiver._write (/cube/node_modules/ws/lib/receiver.js:78:10)\n    at doWrite (_stream_writable.js:403:12)\n    at writeOrBuffer (_stream_writable.js:387:5)\n    at Receiver.Writable.write (_stream_writable.js:318:11)\n    at Socket.socketOnData (/cube/node_modules/ws/lib/websocket.js:1102:35)\n    at Socket.emit (events.js:314:20)\n    at addChunk (_stream_readable.js:297:12)\n    at readableAddChunk (_stream_readable.js:272:9)\n    at Socket.Readable.push (_stream_readable.js:213:10)\n    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)"}
Uploading external pre-aggregation error: {"queryKey":[["CREATE TABLE cube.clickstream_product_view_count_by_product_id_and_seller_id20211126 ENGINE = MergeTree() ORDER BY (`clickstream_product_view__product_id`, `clickstream_product_to_seller_dict__seller_id`) AS SELECT\n      `clickstream_product_to_seller_dict`.seller_id `clickstream_product_to_seller_dict__seller_id`, `clickstream_product_view`.product_id `clickstream_product_view__product_id`, toDateTime(toStartOfDay(toTimeZone(toDateTime(`clickstream_product_view`.received_at), 'UTC'), 'UTC'), 'UTC') `clickstream_product_view__received_at_day`, count(`clickstream_product_view`.event_id) `clickstream_product_view__count`\n    FROM\n      (SELECT * FROM kazanexpress.events WHERE event_type = 'PRODUCT_VIEW') AS `clickstream_product_view`\nLEFT JOIN kazanexpress.product_id_to_seller_id AS `clickstream_product_to_seller_dict` ON `clickstream_product_view`.product_id = `clickstream_product_to_seller_dict`.product_id  WHERE (`clickstream_product_view`.received_at >= parseDateTimeBestEffort(?) AND `clickstream_product_view`.received_at <= parseDateTimeBestEffort(?)) GROUP BY `clickstream_product_to_seller_dict__seller_id`, `clickstream_product_view__product_id`, `clickstream_product_view__received_at_day`",["2021-11-26T00:00:00.000Z","2021-11-26T23:59:59.999Z"],{}],[{"indexName":"clickstream_product_view_count_by_product_id_and_seller_id_product_ids_index","sql":["CREATE INDEX clickstream_product_view_count_by_product_id_and_seller_id_product_ids_index ON cube.clickstream_product_view_count_by_product_id_and_seller_id20211126 (`clickstream_product_view__product_id`, `clickstream_product_to_seller_dict__seller_id`)",[],{}]}],[[{"refresh_key":null}]]],"query":"SELECT\n      `clickstream_product_to_seller_dict`.seller_id `clickstream_product_to_seller_dict__seller_id`, `clickstream_product_view`.product_id `clickstream_product_view__product_id`, toDateTime(toStartOfDay(toTimeZone(toDateTime(`clickstream_product_view`.received_at), 'UTC'), 'UTC'), 'UTC') `clickstream_product_view__received_at_day`, count(`clickstream_product_view`.event_id) `clickstream_product_view__count`\n    FROM\n      (SELECT * FROM kazanexpress.events WHERE event_type = 'PRODUCT_VIEW') AS `clickstream_product_view`\nLEFT JOIN kazanexpress.product_id_to_seller_id AS `clickstream_product_to_seller_dict` ON `clickstream_product_view`.product_id = `clickstream_product_to_seller_dict`.product_id  WHERE (`clickstream_product_view`.received_at >= parseDateTimeBestEffort(?) AND `clickstream_product_view`.received_at <= parseDateTimeBestEffort(?)) GROUP BY `clickstream_product_to_seller_dict__seller_id`, `clickstream_product_view__product_id`, `clickstream_product_view__received_at_day`","values":["2021-11-26T00:00:00.000Z","2021-11-26T23:59:59.999Z"],"targetTableName":"cube.clickstream_product_view_count_by_product_id_and_seller_id20211126_ywxrr1oc_1dkhgwqu_1gq9nas","requestId":"43a84184395c018466c273359bc08c2c","newVersionEntry":{"table_name":"cube.clickstream_product_view_count_by_product_id_and_seller_id20211126","structure_version":"1dkhgwqu","content_version":"ywxrr1oc","last_updated_at":1638194524842,"naming_version":2},"error":"Error: Error during create table: CREATE TABLE cube.clickstream_product_view_count_by_product_id_and_seller_id20211126_ywxrr1oc_1dkhgwqu_1gq9nas (`clickstream_product_to_seller_dict__seller_id` Nullable(UInt64), `clickstream_product_view__product_id` bigint, `clickstream_product_view__received_at_day` timestamp, `clickstream_product_view__count` bigint) INDEX clickstream_product_view_count_by_product_id_and_seller_id_product_ids_index_ywxrr1oc_1dkhgwqu_1gq9nas (`clickstream_product_view__product_id`, `clickstream_product_to_seller_dict__seller_id`) LOCATION ?: Internal: ParserError(\"Expected ',' or ')' after column definition, found: (\")\n    at WebSocket.<anonymous> (/cube/node_modules/@cubejs-backend/cubestore-driver/src/WebSocketConnection.ts:87:30)\n    at WebSocket.emit (events.js:314:20)\n    at Receiver.receiverOnMessage (/cube/node_modules/ws/lib/websocket.js:1008:20)\n    at Receiver.emit (events.js:314:20)\n    at Receiver.dataMessage (/cube/node_modules/ws/lib/receiver.js:502:14)\n    at Receiver.getData (/cube/node_modules/ws/lib/receiver.js:435:17)\n    at Receiver.startLoop (/cube/node_modules/ws/lib/receiver.js:143:22)\n    at Receiver._write (/cube/node_modules/ws/lib/receiver.js:78:10)\n    at doWrite (_stream_writable.js:403:12)\n    at writeOrBuffer (_stream_writable.js:387:5)\n    at Receiver.Writable.write (_stream_writable.js:318:11)\n    at Socket.socketOnData (/cube/node_modules/ws/lib/websocket.js:1102:35)\n    at Socket.emit (events.js:314:20)\n    at addChunk (_stream_readable.js:297:12)\n    at readableAddChunk (_stream_readable.js:272:9)\n    at Socket.Readable.push (_stream_readable.js:213:10)\n    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)"}
```
Cube:

```
cube('ClickstreamProductView', {
    sql: `SELECT * FROM kazanexpress.events WHERE event_type = \'PRODUCT_VIEW\'`,
    dataSource: `clickhouse`,

    joins: {
        ClickstreamProductToSellerDict: {
            relationship: `hasOne`,
            sql: `${CUBE}.product_id = ${ClickstreamProductToSellerDict}.product_id`
        }
    },

    measures : {
        auditory: {
            type: `countDistinct`,
            sql: `account_id`,
            drillMembers: [`${CUBE}.productId`, ClickstreamProductToSellerDict.sellerId, ClickstreamProductToSellerDict.shopId]
        },

        count: {
            type: `count`,
            drillMembers: [`${CUBE}.productId`, ClickstreamProductToSellerDict.sellerId, ClickstreamProductToSellerDict.shopId]
        }
    },

    dimensions: {
        id: {
            sql: `${CUBE}.event_id`,
            type: `string`,
            primaryKey: true,
        },
        receivedAt: {
            sql: `received_at`,
            type: `time`
        },
        productId: {
            sql: `product_id`,
            type: `number`
        },
    },

    preAggregations: {
        countByProductIdAndSellerId: {
            type: `rollup`,
            measures: [
                ClickstreamProductView.count,
            ],
            dimensions: [
                ClickstreamProductView.productId,
                ClickstreamProductToSellerDict.sellerId
            ],
            timeDimension: ClickstreamProductView.receivedAt,
            partitionGranularity: `day`,
            scheduledRefresh: true,
            granularity: `day`,
            refreshKey: {
                every: `30 minute`,
                incremental: true,
                updateWindow: `1 day`,
            },
            buildRangeStart: {
                sql: `SELECT NOW() - interval '60 day'`,
            },
            buildRangeEnd: {
                sql: `SELECT NOW()`,
            },
            indexes: {
                product_ids_index: {
                    columns: [
                        ClickstreamProductView.productId,
                        ClickstreamProductToSellerDict.sellerId
                    ]
                }
            }
        },
    }
});
```
**Expected behaviour**
Pre-aggregation table with index correctly creates

**Version:**
v0.28.60

**Additional context**
Thread in Slack: https://cube-js.slack.com/archives/CC0403RRR/p1638194640341800

**Comment by paveltiunov** [comment]
@olejeglejeg Hey Oleg! Thanks for posting this one! Generally speaking, this use case is no longer supported. You should use Cube Store instead. However, we're open to community contributions here!

**Comment by olejeglejeg** [comment]
@paveltiunov Hmmm, it's strange, since we already have cube platform setup with Cube Store. Should we add some additional configuration to enable Cube Store for ClickHouse?
At the moment we added Clickhouse to dbType and driverFactory inside cube.js file.

**Comment by olejeglejeg** [comment]
@paveltiunov Can somebody from Cube team give us advice on what we do wrong?

**Comment by paveltiunov** [comment]
@olejeglejeg Please make sure `CUBEJS_EXTERNAL_DEFAULT` is set to `true`.

**Comment by yudain** [comment]
@paveltiunov We are facing the same error when Cube creates pre-aggregation. Also, I tried to set `CUBEJS_EXTERNAL_DEFAULT=true`  or `external: true` but it seems Cube doesn't recognize them. Cube continues to try creating a table on CH.

**Comment by ifokeev** [comment]
Same issue here.
@paveltiunov could you help, please? 
Getting: `Error: ClickHouse doesn't support pre-aggregations without indexes`

**Comment by NoudEmonts** [comment]
We are experiencing the same issues on v0.33.33
@paveltiunov any progress on this issue?

**Comment by fbloo** [comment]
Turned out, our issue was that we tried to use an UUID column as index.

**Comment by igorlukanin** [comment]
I've tried to reproduce the original issue with the following simplified data model on Cube v0.36.7 and it looks like it works without any problems now:

```yaml
cube('ClickstreamProductToSellerDict', {
    sql: `SELECT 456 AS seller_id, 123 AS product_id`,

    dimensions: {
      sellerId: {
        sql: `seller_id`,
        type: `number`
      },
      productId: {
        sql: `product_id`,
        type: `number`,
        primaryKey: true
      },
    },
})

cube('ClickstreamProductView', {
    sql: `SELECT '2025-01-01'::TIMESTAMP AS received_at, 123 AS product_id`,

    joins: {
      ClickstreamProductToSellerDict: {
        relationship: `hasOne`,
        sql: `${CUBE}.product_id = ${ClickstreamProductToSellerDict}.product_id`
      }
    },

    measures: {
      count: {
        type: `count`
      }
    },

    dimensions: {
      receivedAt: {
        sql: `received_at`,
        type: `time`
      },
      productId: {
        sql: `product_id`,
        type: `number`,
        primaryKey: true
      },
    },

    preAggregations: {
      countByProductIdAndSellerId: {
        type: `rollup`,
        measures: [
          ClickstreamProductView.count,
        ],
        dimensions: [
          ClickstreamProductView.productId,
          ClickstreamProductToSellerDict.sellerId
        ],
        timeDimension: ClickstreamProductView.receivedAt,
        scheduledRefresh: true,
        granularity: `day`,
        indexes: {
          product_ids_index: {
            columns: [
              ClickstreamProductView.productId,
              ClickstreamProductToSellerDict.sellerId
            ]
          }
        }
      },
    }
});
```

The pre-aggregation builds:

<img width="1392" alt="Screenshot 2024-10-09 at 12 51 08" src="https://github.com/user-attachments/assets/5e46e687-8510-4750-bd7d-57e122cd4138">
