### ISSUE TITLE
BigQuery error with multiple primaryKeys: Error: Type not found: TEXT

### ISSUE THREAD

**Issue by frimuchkov** [cube-js/cube#4445]
We found this error on v0.29.52 (tried to upgrade from v0.29.41), we use BQ driver

```
{
  "insertId": "n2982z34ba32xbyy",
  "jsonPayload": {
    "error": "Error: Type not found: TEXT at [2:56]\n    at QueryQueue.parseResult (/cube/node_modules/@cubejs-backend/query-orchestrator/src/orchestrator/QueryQueue.js:138:13)\n    at QueryQueue.executeInQueue (/cube/node_modules/@cubejs-backend/query-orchestrator/src/orchestrator/QueryQueue.js:127:19)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at /cube/node_modules/@cubejs-backend/query-orchestrator/src/orchestrator/QueryCache.ts:339:17\n    at QueryOrchestrator.fetchQuery (/cube/node_modules/@cubejs-backend/query-orchestrator/src/orchestrator/QueryOrchestrator.ts:120:20)\n    at OrchestratorApi.executeQuery (/cube/node_modules/@cubejs-backend/server-core/src/core/OrchestratorApi.ts:57:20)\n    at /cube/node_modules/@cubejs-backend/api-gateway/src/gateway.ts:795:21\n    at async Promise.all (index 0)\n    at ApiGateway.getSqlResponseInternal (/cube/node_modules/@cubejs-backend/api-gateway/src/gateway.ts:793:31)\n    at /cube/node_modules/@cubejs-backend/api-gateway/src/gateway.ts:920:28\n    at async Promise.all (index 0)\n    at ApiGateway.load (/cube/node_modules/@cubejs-backend/api-gateway/src/gateway.ts:911:23)\n    at /cube/node_modules/@cubejs-backend/api-gateway/src/gateway.ts:174:7",
    "message": "Error querying db",
    "requestId": "253a0536-d953-4689-b29c-d1af2d197f22-span-1",
    "query": "SELECT count(CONCAT(CAST(`conversions`.conversion_id as TEXT), CAST(`conversions`.session_id as TEXT))) `conversions__count`, sum(`conversions`.conversion_value) `conversions__conversion_value`, sum(`conversions`.conversion_credit) `conversions__conversion_credit`, 0 `conversions__not_preaggregated_measure` FROM attribution AS `attribution` LEFT JOIN conversions AS `conversions` ON `attribution`.`sessionId` = `conversions`.session_id WHERE (`conversions`.internal_id = ?) AND (IF(`conversions`.conversion_credit > 0, true, false) = CAST(? AS BOOL)) AND (TIMESTAMP(`attribution`.`date`) >= TIMESTAMP(?) AND TIMESTAMP(`attribution`.`date`) <= TIMESTAMP(?)) LIMIT 50000",
}
```

**Comment by paveltiunov** [comment]
@rccoe You most probably have this issue as well.

**Comment by paveltiunov** [comment]
For those who migrating from earlier versions workaround is to keep only one `primaryKey: true` per cube.

**Comment by igorlukanin** [comment]
I've tested this on Cube v0.36.7 with the following data model and it looks like this works as expected now:

```yaml
cubes:
  - name: test
    sql: SELECT 123 AS id, 456 AS id_2

    dimensions:
      - name: id
        sql: id
        type: number
        primary_key: true

      - name: id_2
        sql: id_2
        type: number
        primary_key: true

    measures:
      - name: count
        type: count
```

Generated SQL:
<img width="1392" alt="Screenshot 2024-10-09 at 02 54 17" src="https://github.com/user-attachments/assets/ecf3ec59-13f1-4830-9aeb-8282b2867482">
