### ISSUE TITLE
UnhandledPromiseRejectionWarning on GraphQL query when using k8s ConfigMap for schema

### ISSUE THREAD

**Issue by benchoncy** [cube-js/cube#5357]
**Describe the bug**
When running cube in k8s and attaching the schema files through a `ConfigMap`, the below error is raised in the container, and no response is received.

```
(node:1) UnhandledPromiseRejectionWarning: Error: xyz was already defined and imported as a type, check the docs for extending types
    at extendError (/cube/node_modules/nexus/src/builder.ts:1743:10)
    at SchemaBuilder.addType (/cube/node_modules/nexus/src/builder.ts:602:15)
    at SchemaBuilder.addTypes (/cube/node_modules/nexus/src/builder.ts:708:12)
    at /cube/node_modules/nexus/src/builder.ts:710:39
    at Array.forEach (<anonymous>)
    at SchemaBuilder.addTypes (/cube/node_modules/nexus/src/builder.ts:710:13)
    at makeSchemaInternal (/cube/node_modules/nexus/src/builder.ts:1763:11)
    at Object.makeSchema (/cube/node_modules/nexus/src/makeSchema.ts:14:67)
    at Object.makeSchema (/cube/node_modules/@cubejs-backend/api-gateway/src/graphql.ts:608:10)
    at /cube/node_modules/@cubejs-backend/api-gateway/src/gateway.ts:166:18
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

**To Reproduce**
Steps to reproduce the behaviour:
1. Deploy cube to k8s. I used the [example helm chart](https://github.com/cube-js/cube.js/tree/master/examples/helm-charts)
2. Create a schema as described in the [example cubejs helm chart](https://github.com/cube-js/cube.js/tree/master/examples/helm-charts/cubejs#injecting-schema) using a `ConfigMap`
3. Query the `/cubejs-api/graphql/` route

**Expected behaviour**
GraphQL query to return a response successfully.

**Screenshots**
N/A

**Minimally reproducible Cube Schema**
N/A - unrelated to the schema itself

**Version:**
v0.30.75

**Additional context**
The use of `ConfigMap` does not affect the REST API; the issue appears to arise from hidden symlinks appearing when using a `ConfigMap`. [Similar problem from Slack](https://cube-js.slack.com/archives/CC0403RRR/p1662634531775179)

**Comment by benchoncy** [comment]
I believe the root of this issue is with the Nexus node module, however, I think:
- Cube should provide a helpful error message in this case if possible.
- Remove the recommendation to use `ConfigMap` from the helm examples.

**Comment by lvauvillier** [comment]
@benchoncy you can fix this issue using a custom repositoryFactory.
More details here: https://github.com/gadsme/charts/tree/main/charts/cube#fix-duplicate-schemas-issue
