### ISSUE TITLE
Connection Refused- Metabase and CubeJs Integration

### ISSUE THREAD

**Issue by ShreyasSheshagiri** [cube-js/cube#5899]
1. Facing the Connection Refused Error while connecting between CubeJs and Metabase

**Git Path**:
https://github.com/cube-js/cube.js/blob/master/examples/metabase/docker-compose.yaml

**Error**:
```
Caused by: org.postgresql.util.PSQLException: Connection to postgres:54320 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
        at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:319)
        at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
        at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:247)
        at org.postgresql.Driver.makeConnection(Driver.java:434)
        at org.postgresql.Driver.connect(Driver.java:291)
        at java.sql/java.sql.DriverManager.getConnection(Unknown Source)
        at java.sql/java.sql.DriverManager.getConnection(Unknown Source)
        at metabase.db.data_source.DataSource.getConnection(data_source.clj:25)
        at com.mchange.v2.c3p0.WrapperConnectionPoolDataSource.getPooledConnection(WrapperConnectionPoolDataSource.java:161)
        at com.mchange.v2.c3p0.WrapperConnectionPoolDataSource.getPooledConnection(WrapperConnectionPoolDataSource.java:147)
        at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.acquireResource(C3P0PooledConnectionPool.java:202)
        at com.mchange.v2.resourcepool.BasicResourcePool.doAcquire(BasicResourcePool.java:1176)
        at com.mchange.v2.resourcepool.BasicResourcePool.doAcquireAndDecrementPendingAcquiresWithinLockOnSuccess(BasicResourcePool.java:1163)
        at com.mchange.v2.resourcepool.BasicResourcePool.access$700(BasicResourcePool.java:44)
        at com.mchange.v2.resourcepool.BasicResourcePool$ScatteredAcquireTask.run(BasicResourcePool.java:1908)
        at com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread.run(ThreadPoolAsynchronousRunner.java:696)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
        at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.base/java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
        at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
        at java.base/java.net.AbstractPlainSocketImpl.connect(Unknown Source)
        at java.base/java.net.SocksSocketImpl.connect(Unknown Source)
        at java.base/java.net.Socket.connect(Unknown Source)
        at org.postgresql.core.PGStream.createSocket(PGStream.java:241)
        at org.postgresql.core.PGStream.<init>(PGStream.java:98)
        at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:109)
        at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:235)
        ... 15 more
2023-01-02 11:25:49,460 INFO metabase.core :: Metabase Shutting Down ...
2023-01-02 11:25:49,465 INFO metabase.server :: Shutting Down Embedded Jetty Webserver
2023-01-02 11:25:49,471 WARN server.AbstractConnector :: 
java.io.IOException: Thread signal failed
        at java.base/sun.nio.ch.NativeThread.signal(Native Method)
        at
```

**Comment by igorlukanin** [comment]
Hi @ShreyasSheshagiri 👋 It looks like an issue with the Postgres container: https://github.com/cube-js/cube/blob/master/examples/metabase/docker-compose.yaml#L15,L25

It's hard to say what happened to that one, logs might have shed some light on it. Please feel free to reopen this issue to follow up
