### ISSUE TITLE
Tab "Dashboard app" not opening

### ISSUE THREAD

**Issue by nikolasj** [cube-js/cube#6007]
**Describe the bug**
When I go to Dashboard app, I get an error.
**To Reproduce**
1. Go to 'Dashboard app'
2. Click on 'developer tools'
3. See error

**Logs:**
```
FetchError: invalid json response body at https://api.github.com/repos/cube-js/cubejs-playground-templates/contents/manifest.json reason: Unexpected token < in JSON at position 0
    at /cube/node_modules/node-fetch/lib/index.js:273:32
    at processTicksAndRejections (/internal/process/task_queues.js:95:5)
    at PackageFetcher.manifestJSON (/cube/node_modules/@cubejs-backend/templates/src/PackageFetcher.ts:46:36)
    at /cube/node_modules/@cubejs-backend/server-core/src/core/DevServer.ts:380:16
    at /cube/node_modules/@cubejs-backend/server-core/src/core/DevServer.ts:78:9
```

**Version:**
some versions check. last and previos

**Comment by paveltiunov** [comment]
@nikolasj It might be your network settings don't allow you to access GitHub.
