### ISSUE TITLE
Redshift changes order of preaggregation table columns causing union all to fail when filtering over date ranges that extend through multiple tables

### ISSUE THREAD

**Issue by jskarda829** [cube-js/cube#6023]
**Describe the bug**
When querying data preaggregated from Redshift on a monthly scale, the tables can have their columns ordered differently causing the union all between the tables of the generated query to fail because of the different schema. 

**To Reproduce**
1. Have multiple years of data in Redshift to be preaggregated.
2. Preaggregate based on the following, using S3 Export Bucket(full cube setup further down)
```preAggregations: {
    action_count: {
      measures: [Actions.count],
      dimensions: [
            PropertyActions1.property_id, 
            PropertyActions2.property_id,
            PropertyActions3.property_id, 
            PropertyActions4.property_id, 
            PropertyActions5.property_id,
            PropertyActions6.property_id, 
            Actions.action_type
      ],
      indexes: {
        property1Index: {
          columns: [PropertyActions1.property_id]
        },
        property2Index: {
          columns: [PropertyActions2.property_id]
        },
        property3Index: {
          columns: [PropertyActions3.property_id]
        },
        property4Index: {
          columns: [PropertyActions4.property_id]
        },
        property5Index: {
          columns: [PropertyActions5.property_id]
        },
        property6Index: {
          columns: [PropertyActions6.property_id]
        }
      },
      timeDimension: Actions.timestamp,
      granularity: `day`,
      partitionGranularity: `month`,
      refreshKey: {
        every: `1 day`,
        incremental: true,
        updateWindow: `7 day`
      }
    },
  }
  ```
3. Query for all dimensions for all time and you may receive a UNION ALL error.
4. Using the MySQL CLI client, run ```select * from system.tables```. The column orders will be different.

**Expected behavior**
Expected behavior is that querying on preaggregations across all time works.
Actual behavior is that if the preaggregations have differently ordered columns the query fails because the table schema is different between them.

**Error messages and output**
```cube_1                 | Error while querying: e8d6320f-86ed-43bf-b906-b83494081d06-span-1 (12ms)
cube_1                 | {
cube_1                 |   "queueSize": 0,
cube_1                 |   "queryKey": [
cube_1                 |     "SELECT `actions__action_type` `actions__action_type`, `property_actions2__property_id` `property_actions2__property_id`, `property_actions1__property_id` `property_actions1__property_id`, `property_actions3__property_id` `property_actions3__property_id`, `property_actions4__property_id` `property_actions4__property_id`, `property_actions5__property_id` `property_actions5__property_id`, `property_actions6__property_id` `property_actions6__property_id`, sum(`actions__count`) `actions__count` FROM (SELECT * FROM dev_pre_aggregations.actions_action_count20210801_vntn2w04_kopwep44_1hs2s1j UNION ALL SELECT * FROM dev_pre_aggregations.actions_action_count20210901_ibnelmmw_zwtjncmk_1hs2s1j) AS `actions__action_count`  WHERE (`actions__timestamp_day` >= to_timestamp(?) AND `actions__timestamp_day` <= to_timestamp(?)) GROUP BY 1, 2, 3, 4, 5, 6, 7 ORDER BY 8 DESC LIMIT 100",
cube_1                 |     [
cube_1                 |       "2021-08-01T00:00:00.000",
cube_1                 |       "2021-09-30T23:59:59.999"
cube_1                 |     ]
cube_1                 |   ],
cube_1                 |   "queuePrefix": "SQL_QUERY_EXT_STANDALONE",
cube_1                 |   "timeInQueue": 0
cube_1                 | } 
cube_1                 | Error: Internal: Error during planning: UNION ALL schemas are expected to be the same
cube_1                 |     at WebSocket.<anonymous> (/cube/node_modules/@cubejs-backend/cubestore-driver/src/WebSocketConnection.ts:117:30)
cube_1                 |     at WebSocket.emit (events.js:400:28)
cube_1                 |     at Receiver.receiverOnMessage (/cube/node_modules/ws/lib/websocket.js:1008:20)
cube_1                 |     at Receiver.emit (events.js:400:28)
cube_1                 |     at Receiver.dataMessage (/cube/node_modules/ws/lib/receiver.js:502:14)
cube_1                 |     at Receiver.getData (/cube/node_modules/ws/lib/receiver.js:435:17)
cube_1                 |     at Receiver.startLoop (/cube/node_modules/ws/lib/receiver.js:143:22)
cube_1                 |     at Receiver._write (/cube/node_modules/ws/lib/receiver.js:78:10)
cube_1                 |     at writeOrBuffer (internal/streams/writable.js:358:12)
cube_1                 |     at Receiver.Writable.write (internal/streams/writable.js:303:10)
cube_1                 |     at Socket.socketOnData (/cube/node_modules/ws/lib/websocket.js:1102:35)
cube_1                 |     at Socket.emit (events.js:400:28)
cube_1                 |     at addChunk (internal/streams/readable.js:293:12)
cube_1                 |     at readableAddChunk (internal/streams/readable.js:267:9)
cube_1                 |     at Socket.Readable.push (internal/streams/readable.js:206:10)
cube_1                 |     at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
cube_1                 | Error querying db: e8d6320f-86ed-43bf-b906-b83494081d06-span-1 
cube_1                 | --
cube_1                 | "SELECT `actions__action_type` `actions__action_type`, `property_actions2__property_id` `property_actions2__property_id`, `property_actions1__property_id` `property_actions1__property_id`, `property_actions3__property_id` `property_actions3__property_id`, `property_actions4__property_id` `property_actions4__property_id`, `property_actions5__property_id` `property_actions5__property_id`, `property_actions6__property_id` `property_actions6__property_id`, sum(`actions__count`) `actions__count` FROM dev_pre_aggregations.actions_action_count AS `actions__action_count` WHERE (`actions__timestamp_day` >= to_timestamp(?) AND `actions__timestamp_day` <= to_timestamp(?)) GROUP BY 1, 2, 3, 4, 5, 6, 7 ORDER BY 8 DESC LIMIT 100"
cube_1                 | --
cube_1                 | {
cube_1                 |   "params": [
cube_1                 |     "2021-08-01T00:00:00.000",
cube_1                 |     "2021-09-30T23:59:59.999"
cube_1                 |   ]
cube_1                 | } 
cube_1                 | Error: Internal: Error during planning: UNION ALL schemas are expected to be the same
cube_1                 |     at QueryQueue.parseResult (/cube/node_modules/@cubejs-backend/query-orchestrator/src/orchestrator/QueryQueue.js:236:13)
cube_1                 |     at QueryQueue.executeInQueue (/cube/node_modules/@cubejs-backend/query-orchestrator/src/orchestrator/QueryQueue.js:139:19)
cube_1                 |     at processTicksAndRejections (internal/process/task_queues.js:95:5)
cube_1                 |     at QueryCache.cachedQueryResult (/cube/node_modules/@cubejs-backend/query-orchestrator/src/orchestrator/QueryCache.ts:209:15)
cube_1                 |     at QueryOrchestrator.fetchQuery (/cube/node_modules/@cubejs-backend/query-orchestrator/src/orchestrator/QueryOrchestrator.ts:224:20)
cube_1                 |     at OrchestratorApi.executeQuery (/cube/node_modules/@cubejs-backend/server-core/src/core/OrchestratorApi.ts:86:20)
cube_1                 |     at /cube/node_modules/@cubejs-backend/api-gateway/src/gateway.ts:1235:21
cube_1                 |     at async Promise.all (index 0)
cube_1                 |     at ApiGateway.getSqlResponseInternal (/cube/node_modules/@cubejs-backend/api-gateway/src/gateway.ts:1233:31)
cube_1                 |     at /cube/node_modules/@cubejs-backend/api-gateway/src/gateway.ts:1362:28
cube_1                 |     at async Promise.all (index 0)
cube_1                 |     at ApiGateway.load (/cube/node_modules/@cubejs-backend/api-gateway/src/gateway.ts:1353:23)
cube_1                 |     at /cube/node_modules/@cubejs-backend/api-gateway/src/gateway.ts:197:7
cube_1                 | Orchestrator error: e8d6320f-86ed-43bf-b906-b83494081d06-span-1 (112ms)
cube_1                 | --
cube_1                 | {
cube_1                 |   "measures": [
cube_1                 |     "Actions.count"
cube_1                 |   ],
cube_1                 |   "limit": 100,
cube_1                 |   "dimensions": [
cube_1                 |     "Actions.action_type",
cube_1                 |     "PropertyActions2.property_id",
cube_1                 |     "PropertyActions1.property_id",
cube_1                 |     "PropertyActions3.property_id",
cube_1                 |     "PropertyActions4.property_id",
cube_1                 |     "PropertyActions5.property_id",
cube_1                 |     "PropertyActions6.property_id"
cube_1                 |   ],
cube_1                 |   "order": {
cube_1                 |     "Actions.count": "desc"
cube_1                 |   },
cube_1                 |   "timeDimensions": [
cube_1                 |     {
cube_1                 |       "dimension": "Actions.timestamp",
cube_1                 |       "dateRange": [
cube_1                 |         "2021-08-01",
cube_1                 |         "2021-09-30"
cube_1                 |       ]
cube_1                 |     }
cube_1                 |   ]
cube_1                 | }
cube_1                 | --
cube_1                 | {
cube_1                 |   "securityContext": {
cube_1                 |     "appname": "placeholder",
cube_1                 |     "userlang": "en-us",
cube_1                 |     "iat": 1673966692
cube_1                 |   }
cube_1                 | } 
cube_1                 | Error: Internal: Error during planning: UNION ALL schemas are expected to be the same
```

```
|   25 |         1 | dev_pre_aggregations | actions_action_count20210901_ibnelmmw_zwtjncmk_1hs2s1j        | 
[Column { name: "property_actions2__property_id", column_type: String, column_index: 0 }, 
Column { name: "property_actions1__property_id", column_type: String, column_index: 1 }, 
Column { name: "actions__action_type", column_type: String, column_index: 2 }, 
Column { name: "property_actions6__property_id", column_type: String, column_index: 3 }, 
Column { name: "property_actions5__property_id", column_type: String, column_index: 4 }, 
Column { name: "property_actions4__property_id", column_type: String, column_index: 5 }, 
Column { name: "property_actions3__property_id", column_type: String, column_index: 6 }, 
Column { name: "actions__count", column_type: Int, column_index: 7 }, 
Column { name: "actions__timestamp_day", column_type: Timestamp, column_index: 8 }] | 

|   26 |         1 | dev_pre_aggregations | actions_action_count20210801_vntn2w04_kopwep44_1hs2s1j        | 
[Column { name: "property_actions1__property_id", column_type: String, column_index: 0 }, 
Column { name: "actions__action_type", column_type: String, column_index: 1 }, 
Column { name: "property_actions6__property_id", column_type: String, column_index: 2 }, 
Column { name: "property_actions5__property_id", column_type: String, column_index: 3 }, 
Column { name: "property_actions4__property_id", column_type: String, column_index: 4 }, 
Column { name: "property_actions3__property_id", column_type: String, column_index: 5 }, 
Column { name: "property_actions2__property_id", column_type: String, column_index: 6 }, 
Column { name: "actions__count", column_type: Int, column_index: 7 }, 
Column { name: "actions__timestamp_day", column_type: Timestamp, column_index: 8 }] | 
```

**Screenshots**
![august-success](https://user-images.githubusercontent.com/13393237/213015581-92d11bf4-8fcb-4ff5-a2b8-b4abb469bb1f.png)
![september-success](https://user-images.githubusercontent.com/13393237/213015619-efc814a4-951a-4dbc-ab06-cdec297ea035.png)
![unionall-error](https://user-images.githubusercontent.com/13393237/213015628-ae0e1ac0-3112-48c0-9513-d56c45fad048.png)

**Minimally reproducible Cube Schema**

```javascript
cube(`Actions`, {
  sql: `SELECT * FROM ${appname}.v_fact_user_activity_full`,
  measures: {
    count: {
      type: `count`
    }
  },
  dimensions: {
    action_id: {
      sql: `action_id`,
      type: `string`,
      shown: true,
      primaryKey: true
    },
    action_type: {
      sql: `action_type`,
      type: `string`
    },
    timestamp: {
      sql: `timestamp`,
      type: `time`
    },
    user_id: {
      sql: `user_id`,
      type: `string`
    },
    applicationname: {
      sql: `applicationname`,
      type: `string`
    }
  },
  joins: {
    PropertyActions1: {
      relationship: `hasMany`,
      sql: `${CUBE.action_id} = ${PropertyActions1.action_id}`
    },
    PropertyActions2: {
      relationship: `hasMany`,
      sql: `${CUBE.action_id} = ${PropertyActions2.action_id}`
    },
    PropertyActions3: {
      relationship: `hasMany`,
      sql: `${CUBE.action_id} = ${PropertyActions3.action_id}`
    },
    PropertyActions4: {
      relationship: `hasMany`,
      sql: `${CUBE.action_id} = ${PropertyActions4.action_id}`
    },
    PropertyActions5: {
      relationship: `hasMany`,
      sql: `${CUBE.action_id} = ${PropertyActions5.action_id}`
    },
    PropertyActions6: {
      relationship: `hasMany`,
      sql: `${CUBE.action_id} = ${PropertyActions6.action_id}`
    },
  },
  preAggregations: {
    action_count: {
      measures: [Actions.count],
      dimensions: [
            PropertyActions1.property_id, 
            PropertyActions2.property_id,
            PropertyActions3.property_id, 
            PropertyActions4.property_id, 
            PropertyActions5.property_id,
            PropertyActions6.property_id, 
            Actions.action_type
      ],
      indexes: {
        property1Index: {
          columns: [PropertyActions1.property_id]
        },
        property2Index: {
          columns: [PropertyActions2.property_id]
        },
        property3Index: {
          columns: [PropertyActions3.property_id]
        },
        property4Index: {
          columns: [PropertyActions4.property_id]
        },
        property5Index: {
          columns: [PropertyActions5.property_id]
        },
        property6Index: {
          columns: [PropertyActions6.property_id]
        }
      },
      timeDimension: Actions.timestamp,
      granularity: `day`,
      partitionGranularity: `month`,
      refreshKey: {
        every: `1 day`,
        incremental: true,
        updateWindow: `7 day`
      }
    },
  }
});
//There are 6 of these which are identical apart from the number, only included one for brevity
cube('PropertyActions1', {
  sql: `SELECT * FROM ${appname}.v_bridge_action_id_property_id_1`,
  
  dimensions: {
      id: {
          sql: `CONCAT(${CUBE}.property_id, ${CUBE}.action_id)`,
          type: `number`,
          primaryKey: true,
      },
      property_id: {
          sql: 'property_id',
          type: 'string',
          shown: true
      },
      action_id: {
          sql: 'action_id',
          type: 'string',
          shown: false
      },
      property_type: {
          sql: 'property_type',
          type: 'string',
          shown: false
      }
  },
});
```

**Version:**
[0.31.32]

**Additional context**
From @paveltiunov on Cube Slack - "It seems Redshift changes order of columns and we need similar fix as for Athena."

**Comment by rdwoodring** [comment]
Interested in chipping in on the fix here with guidance, especially if it's something where referencing the similar fix applied to Athena can pretty heavily guide this fix

**Comment by paveltiunov** [comment]
@rdwoodring It would be great! Here's the same place in AthenaDriver https://github.com/cube-js/cube.js/blob/eedd12a18645d2d6faa68a43963a6cb98560b5a6/packages/cubejs-athena-driver/src/AthenaDriver.ts#L208.

**Comment by rdwoodring** [comment]
Want to give the [pull request](https://github.com/cube-js/cube.js/pull/6068) a bump here. I'm not sure if it's stuck or what. It failed one of the CI steps, but the failures seem unrelated to the changes (I might be wrong on that). 

If there's something that needs to be fixed, though, I'm not sure what it it and would love some feedback to resolve it and get this PR through.

**Comment by jtcies** [comment]
Just wanted to flag that we still ran into this issue on Redshift. The fix in the PR above resolves the problem most of the time, but occasionally when querying `information_schema.columns` Redshift can return columns not in their ordinal position. 

Created #6622 which is working for us in our deployment. Not sure if it's the best approach or other implications of that change.

**Comment by jskarda829** [comment]
Implemented the suggested fix for this issue on @jtcies PR which is to order by ordinal_position instead of alphabetically.

**Comment by paveltiunov** [comment]
`CUBEJS_DB_FETCH_COLUMNS_BY_ORDINAL_POSITION=true` should be used to enable the fix.
