### ISSUE TITLE
Pre aggregation: Internal: Error during planning: Invalid function 'try'

### ISSUE THREAD

**Issue by kodeine** [cube-js/cube#6203]
**Describe the bug**
When i add pre-aggregations, i'm getting error `Internal: Error during planning: Invalid function 'try' for prestodb`. Without pre-agg's it runs just fine.

```
cubejs-cube_api-1 | 2023-02-25 16:06:24,067 INFO  [cubestore::metastore::rocks_store] <pid:23> Persisting metastore snapshot: done (304.694375ms)
cubejs-cube_api-1 | Performing query: 6ce12dba-0f76-45e0-ae83-d4d76181ff39-span-1 
cubejs-cube_api-1 | Executing SQL: 6ce12dba-0f76-45e0-ae83-d4d76181ff39-span-1 
cubejs-cube_api-1 | --
cubejs-cube_api-1 |   SELECT MAX(createdAt) FROM REPORTS_CAMPAIGN
cubejs-cube_api-1 | --
cubejs-cube_api-1 | Performing query: 6ce12dba-0f76-45e0-ae83-d4d76181ff39-span-1 
cubejs-cube_api-1 | Executing SQL: 6ce12dba-0f76-45e0-ae83-d4d76181ff39-span-1 
cubejs-cube_api-1 | --
cubejs-cube_api-1 |   SELECT `reports_campaign__campaign_name` `reports_campaign__campaign_name`, `reports_campaign__report_date_day` `reports_campaign__report_date_day`, COALESCE(TRY(sum(`reports_campaign__sales`) / (sum(`reports_campaign__conversions`) * 1.00)), 0) `reports_campaign__aov` FROM (SELECT * FROM dev_pre_aggregations.reports_campaign_table_rollup20210701_dx1rnfsj_evuoiwnh_1hvkbhv UNION ALL SELECT * FROM dev_pre_aggregations.reports_campaign_table_rollup20210801_0u4femv2_wxpxlas0_1hvkbhv UNION ALL SELECT * FROM dev_pre_aggregations.reports_campaign_table_rollup20210901_4czan1l1_hm1pzk5o_1hvkbhv UNION ALL SELECT * FROM dev_pre_aggregations.reports_campaign_table_rollup20211001_ntjnapgj_nrc4qlvo_1hvkbhv UNION ALL SELECT * FROM dev_pre_aggregations.reports_campaign_table_rollup20211101_h0jbelhy_ulvhisk1_1hvkbhv UNION ALL SELECT * FROM dev_pre_aggregations.reports_campaign_table_rollup20211201_n5ffcgcz_vpfxo0wr_1hvkbhv UNION ALL SELECT * FROM dev_pre_aggregations.reports_campaign_table_rollup20220101_afld33dc_4xu5tan4_1hvkbhv UNION ALL SELECT * FROM dev_pre_aggregations.reports_campaign_table_rollup20220201_14xy2ajj_m35g54em_1hvkbhv UNION ALL SELECT * FROM dev_pre_aggregations.reports_campaign_table_rollup20220301_hf40efyu_gf3vku3v_1hvkbhv UNION ALL SELECT * FROM dev_pre_aggregations.reports_campaign_table_rollup20220401_fhtkk1l4_yueqyf5n_1hvkbhv UNION ALL SELECT * FROM dev_pre_aggregations.reports_campaign_table_rollup20220501_n53spds5_hutigpeq_1hvkbhv UNION ALL SELECT * FROM dev_pre_aggregations.reports_campaign_table_rollup20220601_id24qdre_uucrp5rr_1hvkbhv UNION ALL SELECT * FROM dev_pre_aggregations.reports_campaign_table_rollup20220701_bdpqylkt_23crhzj4_1hvkbhv UNION ALL SELECT * FROM dev_pre_aggregations.reports_campaign_table_rollup20220801_g2as4izn_cixeemkb_1hvkbhv UNION ALL SELECT * FROM dev_pre_aggregations.reports_campaign_table_rollup20220901_pyyc3j24_glnqoyqi_1hvkbhv UNION ALL SELECT * FROM dev_pre_aggregations.reports_campaign_table_rollup20221001_zdexox3n_jkj0x1lp_1hvkbhv UNION ALL SELECT * FROM dev_pre_aggregations.reports_campaign_table_rollup20221101_jpg2jtnd_t4zpdzzb_1hvkbhv UNION ALL SELECT * FROM dev_pre_aggregations.reports_campaign_table_rollup20221201_p5wz5v34_aco1ejoh_1hvkbhv UNION ALL SELECT * FROM dev_pre_aggregations.reports_campaign_table_rollup20230101_3j3zisff_k3u4jked_1hvkbhv UNION ALL SELECT * FROM dev_pre_aggregations.reports_campaign_table_rollup20230201_5om5rh5v_g0wcq4xe_1hvkbhv) AS `reports_campaign__table_rollup`  GROUP BY 1, 2 ORDER BY 2 ASC
cubejs-cube_api-1 | --
cubejs-cube_api-1 | 2023-02-25 16:56:46,335 ERROR [cubestore::http] <pid:23> Error processing HTTP command: Internal: Error during planning: Invalid function 'try'
cubejs-cube_api-1 | disabled backtrace
cubejs-cube_api-1 | Error while querying: 6ce12dba-0f76-45e0-ae83-d4d76181ff39-span-1 (7ms)
cubejs-cube_api-1 | {
cubejs-cube_api-1 |   "queueSize": 0,
cubejs-cube_api-1 |   "queryKey": [
cubejs-cube_api-1 |     "SELECT `reports_campaign__campaign_name` `reports_campaign__campaign_name`, `reports_campaign__report_date_day` `reports_campaign__report_date_day`, COALESCE(TRY(sum(`reports_campaign__sales`) / (sum(`reports_campaign__conversions`) * 1.00)), 0) `reports_campaign__aov` FROM (SELECT * FROM dev_pre_aggregations.reports_campaign_table_rollup20210701_dx1rnfsj_evuoiwnh_1hvkbhv UNION ALL SELECT * FROM dev_pre_aggregations.reports_campaign_table_rollup20210801_0u4femv2_wxpxlas0_1hvkbhv UNION ALL SELECT * FROM dev_pre_aggregations.reports_campaign_table_rollup20210901_4czan1l1_hm1pzk5o_1hvkbhv UNION ALL SELECT * FROM dev_pre_aggregations.reports_campaign_table_rollup20211001_ntjnapgj_nrc4qlvo_1hvkbhv UNION ALL SELECT * FROM dev_pre_aggregations.reports_campaign_table_rollup20211101_h0jbelhy_ulvhisk1_1hvkbhv UNION ALL SELECT * FROM dev_pre_aggregations.reports_campaign_table_rollup20211201_n5ffcgcz_vpfxo0wr_1hvkbhv UNION ALL SELECT * FROM dev_pre_aggregations.reports_campaign_table_rollup20220101_afld33dc_4xu5tan4_1hvkbhv UNION ALL SELECT * FROM dev_pre_aggregations.reports_campaign_table_rollup20220201_14xy2ajj_m35g54em_1hvkbhv UNION ALL SELECT * FROM dev_pre_aggregations.reports_campaign_table_rollup20220301_hf40efyu_gf3vku3v_1hvkbhv UNION ALL SELECT * FROM dev_pre_aggregations.reports_campaign_table_rollup20220401_fhtkk1l4_yueqyf5n_1hvkbhv UNION ALL SELECT * FROM dev_pre_aggregations.reports_campaign_table_rollup20220501_n53spds5_hutigpeq_1hvkbhv UNION ALL SELECT * FROM dev_pre_aggregations.reports_campaign_table_rollup20220601_id24qdre_uucrp5rr_1hvkbhv UNION ALL SELECT * FROM dev_pre_aggregations.reports_campaign_table_rollup20220701_bdpqylkt_23crhzj4_1hvkbhv UNION ALL SELECT * FROM dev_pre_aggregations.reports_campaign_table_rollup20220801_g2as4izn_cixeemkb_1hvkbhv UNION ALL SELECT * FROM dev_pre_aggregations.reports_campaign_table_rollup20220901_pyyc3j24_glnqoyqi_1hvkbhv UNION ALL SELECT * FROM dev_pre_aggregations.reports_campaign_table_rollup20221001_zdexox3n_jkj0x1lp_1hvkbhv UNION ALL SELECT * FROM dev_pre_aggregations.reports_campaign_table_rollup20221101_jpg2jtnd_t4zpdzzb_1hvkbhv UNION ALL SELECT * FROM dev_pre_aggregations.reports_campaign_table_rollup20221201_p5wz5v34_aco1ejoh_1hvkbhv UNION ALL SELECT * FROM dev_pre_aggregations.reports_campaign_table_rollup20230101_3j3zisff_k3u4jked_1hvkbhv UNION ALL SELECT * FROM dev_pre_aggregations.reports_campaign_table_rollup20230201_5om5rh5v_g0wcq4xe_1hvkbhv) AS `reports_campaign__table_rollup`  GROUP BY 1, 2 ORDER BY 2 ASC",
cubejs-cube_api-1 |     []
cubejs-cube_api-1 |   ],
cubejs-cube_api-1 |   "queuePrefix": "SQL_QUERY_EXT_STANDALONE",
cubejs-cube_api-1 |   "timeInQueue": 0
cubejs-cube_api-1 | } 
cubejs-cube_api-1 | Error: Internal: Error during planning: Invalid function 'try'
cubejs-cube_api-1 |     at WebSocket.<anonymous> (/cube/node_modules/@cubejs-backend/cubestore-driver/src/WebSocketConnection.ts:121:30)
cubejs-cube_api-1 |     at WebSocket.emit (events.js:400:28)
cubejs-cube_api-1 |     at Receiver.receiverOnMessage (/cube/node_modules/ws/lib/websocket.js:1008:20)
cubejs-cube_api-1 |     at Receiver.emit (events.js:400:28)
cubejs-cube_api-1 |     at Receiver.dataMessage (/cube/node_modules/ws/lib/receiver.js:502:14)
cubejs-cube_api-1 |     at Receiver.getData (/cube/node_modules/ws/lib/receiver.js:435:17)
cubejs-cube_api-1 |     at Receiver.startLoop (/cube/node_modules/ws/lib/receiver.js:143:22)
cubejs-cube_api-1 |     at Receiver._write (/cube/node_modules/ws/lib/receiver.js:78:10)
cubejs-cube_api-1 |     at writeOrBuffer (internal/streams/writable.js:358:12)
cubejs-cube_api-1 |     at Receiver.Writable.write (internal/streams/writable.js:303:10)
cubejs-cube_api-1 |     at Socket.socketOnData (/cube/node_modules/ws/lib/websocket.js:1102:35)
cubejs-cube_api-1 |     at Socket.emit (events.js:400:28)
cubejs-cube_api-1 |     at addChunk (internal/streams/readable.js:293:12)
cubejs-cube_api-1 |     at readableAddChunk (internal/streams/readable.js:267:9)
cubejs-cube_api-1 |     at Socket.Readable.push (internal/streams/readable.js:206:10)
cubejs-cube_api-1 |     at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
cubejs-cube_api-1 | Error querying db: 6ce12dba-0f76-45e0-ae83-d4d76181ff39-span-1 
cubejs-cube_api-1 | --
cubejs-cube_api-1 | "SELECT `reports_campaign__campaign_name` `reports_campaign__campaign_name`, `reports_campaign__report_date_day` `reports_campaign__report_date_day`, COALESCE(TRY(sum(`reports_campaign__sales`) / (sum(`reports_campaign__conversions`) * 1.00)), 0) `reports_campaign__aov` FROM dev_pre_aggregations.reports_campaign_table_rollup AS `reports_campaign__table_rollup` GROUP BY 1, 2 ORDER BY 2 ASC"
cubejs-cube_api-1 | --
cubejs-cube_api-1 | {
cubejs-cube_api-1 |   "params": []
cubejs-cube_api-1 | } 
cubejs-cube_api-1 | Error: Internal: Error during planning: Invalid function 'try'
cubejs-cube_api-1 |     at QueryQueue.parseResult (/cube/node_modules/@cubejs-backend/query-orchestrator/src/orchestrator/QueryQueue.js:416:13)
cubejs-cube_api-1 |     at QueryQueue.executeQueryInQueue (/cube/node_modules/@cubejs-backend/query-orchestrator/src/orchestrator/QueryQueue.js:313:19)
cubejs-cube_api-1 |     at runMicrotasks (<anonymous>)
cubejs-cube_api-1 |     at processTicksAndRejections (internal/process/task_queues.js:95:5)
cubejs-cube_api-1 |     at QueryCache.cachedQueryResult (/cube/node_modules/@cubejs-backend/query-orchestrator/src/orchestrator/QueryCache.ts:269:17)
cubejs-cube_api-1 |     at QueryOrchestrator.fetchQuery (/cube/node_modules/@cubejs-backend/query-orchestrator/src/orchestrator/QueryOrchestrator.ts:257:20)
cubejs-cube_api-1 |     at OrchestratorApi.executeQuery (/cube/node_modules/@cubejs-backend/server-core/src/core/OrchestratorApi.ts:97:20)
cubejs-cube_api-1 |     at /cube/node_modules/@cubejs-backend/api-gateway/src/gateway.ts:1466:21
cubejs-cube_api-1 |     at async Promise.all (index 0)
cubejs-cube_api-1 |     at ApiGateway.getSqlResponseInternal (/cube/node_modules/@cubejs-backend/api-gateway/src/gateway.ts:1464:31)
cubejs-cube_api-1 |     at /cube/node_modules/@cubejs-backend/api-gateway/src/gateway.ts:1637:28
cubejs-cube_api-1 |     at async Promise.all (index 0)
cubejs-cube_api-1 |     at ApiGateway.load (/cube/node_modules/@cubejs-backend/api-gateway/src/gateway.ts:1628:23)
cubejs-cube_api-1 |     at /cube/node_modules/@cubejs-backend/api-gateway/src/gateway.ts:199:7
cubejs-cube_api-1 | Orchestrator error: 6ce12dba-0f76-45e0-ae83-d4d76181ff39-span-1 (75ms)
cubejs-cube_api-1 | --
cubejs-cube_api-1 | {
cubejs-cube_api-1 |   "measures": [
cubejs-cube_api-1 |     "ReportsCampaign.aov"
cubejs-cube_api-1 |   ],
cubejs-cube_api-1 |   "timeDimensions": [
cubejs-cube_api-1 |     {
cubejs-cube_api-1 |       "dimension": "ReportsCampaign.reportDate",
cubejs-cube_api-1 |       "granularity": "day"
cubejs-cube_api-1 |     }
cubejs-cube_api-1 |   ],
cubejs-cube_api-1 |   "order": {
cubejs-cube_api-1 |     "ReportsCampaign.reportDate": "asc"
cubejs-cube_api-1 |   },
cubejs-cube_api-1 |   "dimensions": [
cubejs-cube_api-1 |     "ReportsCampaign.campaignName"
cubejs-cube_api-1 |   ]
cubejs-cube_api-1 | }
cubejs-cube_api-1 | --
cubejs-cube_api-1 | {
cubejs-cube_api-1 |   "securityContext": {
cubejs-cube_api-1 |     "iat": 1677340102,
cubejs-cube_api-1 |     "exp": 1677426502
cubejs-cube_api-1 |   }
cubejs-cube_api-1 | } 
cubejs-cube_api-1 | Error: Internal: Error during planning: Invalid function 'try'
cubejs-cube_api-1 | Performing query completed: 6ce12dba-0f76-45e0-ae83-d4d76181ff39-span-1 (2464ms)
```

```javascript
    aov: {
      type: `number`,
      format: `currency`,
      sql: `COALESCE(TRY(${CUBE.sales} / (${CUBE.conversions} * 1.00)), 0)`,
    },
```

**Version:**
0.31.65
**Prestodb**

**Comment by igorlukanin** [comment]
@paveltiunov @pacofvf Since `TRY` is PrestoDB-specific, what is the best way to decompose this `aov` measure for Cube Store?

**Comment by pacofvf** [comment]
`TRY` only "catches" division by zero, invalid cast argument, and number out of range. In this scenario, the only possible error it can catch is division by zero, so it can be replaced with:
```sql
COALESCE( CASE WHEN ${CUBE.conversions} != 0 THEN ${CUBE.sales} / (${CUBE.conversions} * 1.00) END , 0)
```

**Comment by kodeine** [comment]
@pacofvf i tried with this but i am getting following error,

<img width="871" alt="image" src="https://user-images.githubusercontent.com/8620059/226507345-8ef753d6-3fa3-4436-89c7-1af30b986b53.png">


```
SELECT
  `campaign__targeting_type` `reports_campaign__targeting_type`,
  `reports_campaign__report_date_day` `reports_campaign__report_date_day`,
  COALESCE(
    CASE
      WHEN sum(`reports_campaign__clicks`) != 0 THEN sum(`reports_campaign__sales`) / (sum(`reports_campaign__clicks`) * 1.00)
    END,
    0
  ) `reports_campaign__rpc`
FROM
  dev_pre_aggregations.reports_campaign_table_rollup AS `reports_campaign__table_rollup`
GROUP BY
  1,
  2
ORDER BY
  2 ASC
LIMIT
  5000
```

**Comment by pacofvf** [comment]
Can you try `WHEN ${CUBE.conversions} > 0.0` ? 

if that doesn't work then let's try putting the case when in the denominator.
`COALESCE( CASE WHEN ${CUBE.conversions} > 0.0 THEN ${CUBE.sales} / (CASE WHEN ${CUBE.conversions} > 0.0 THEN ${CUBE.conversions} * 1.00 ELSE 1.0 END) END , 0)`
