### ISSUE TITLE
Cannot run cubejs in development anymore after upgrading to 0.32.16

### ISSUE THREAD

**Issue by velimato** [cube-js/cube#6358]
Hi,

I get this error every time I try to run cubejs in development now.
 
I am using mac OSx. I have tried with my actual application and creating a completely new application with cube cli. Both fail with same error.

 cubejs-test % npm run dev

> cubejs-test@0.0.1 dev
> cubejs-server

🔥 Cube Store (0.32.16) is assigned to 3030 port.
🔓 Authentication checks are disabled in developer mode. Please use NODE_ENV=production to enable it.
🦅 Dev environment available at http://localhost:4000
Fatal error during server start: 
Error: Unable to load @cubejs-backend/native, probably your system (x64-darwin) with Node.js v18.9.0 is not supported.
    at loadNative (/Users/x/Documents/application/cubejs-test/node_modules/@cubejs-backend/native/js/index.ts:71:11)
    at setupLogger (/Users/x/Documents/application/cubejs-test/node_modules/@cubejs-backend/native/js/index.ts:194:20)
    at new SQLServer (/Users/x/Documents/application/cubejs-test/node_modules/@cubejs-backend/api-gateway/src/sql-server.ts:31:16)
    at ApiGateway.initSQLServer (/Users/x/Documents/application/cubejs-test/node_modules/@cubejs-backend/api-gateway/src/gateway.ts:458:12)
    at CubejsServerCore.initSQLServer (/Users/x/Documents/application/cubejs-test/node_modules/@cubejs-backend/server-core/src/core/server.ts:429:23)
    at CubejsServer.listen (/Users/x/Documents/application/cubejs-test/node_modules/@cubejs-backend/server/src/server.ts:120:36)
    at ServerContainer.runServerInstance (/Users/x/Documents/application/cubejs-test/node_modules/@cubejs-backend/server/src/server/container.ts:239:35)
    at makeInstance (/Users/x/Documents/application/cubejs-test/node_modules/@cubejs-backend/server/src/server/container.ts:347:22)
    at ServerContainer.start (/Users/x/Documents/application/cubejs-test/node_modules/@cubejs-backend/server/src/server/container.ts:360:20)
    at Server.run (/Users/x/Documents/application/cubejs-test/node_modules/@cubejs-backend/server/src/command/server.ts:25:5)
    at Server._run (/Users/x/Documents/application/cubejs-test/node_modules/@oclif/command/lib/command.js:43:20)
    at Config.runCommand (/Users/x/Documents/application/cubejs-test/node_modules/@oclif/config/lib/config.js:173:24)
    at Main.run (/Users/x/Documents/application/cubejs-test/node_modules/@oclif/command/lib/main.js:28:9)
    at Main._run (/Users/x/Documents/application/cubejs-test/node_modules/@oclif/command/lib/command.js:43:20)

**Comment by velimato** [comment]
I managed to fix this issue by running cubejs in docker container. But is running cubejs directly with macosx node broken for good now?

**Comment by ovr** [comment]
Hello @velimato ,

Thank you for submitting an issue. 

The last release job for native/darwin failed with a timeout.

https://github.com/cube-js/cube/actions/runs/4536085973/attempts/1

I restarted it and increased the timeout to protect such cases in the future.
It should work after `yarn install`, please do it.

Thanks
