### ISSUE TITLE
Pre-aggregation SQL queries from non-existent column

### ISSUE THREAD

**Issue by tvansteenburgh** [cube-js/cube#6475]
**Describe the bug**
The SQL that is generated for my pre-aggregation attempts to query from a column that doesn't exist. This results in an error (`column keys.r_c__date does not exist`) when the SQL is executed during pre-aggregation refresh.

**To Reproduce**
I've included a minimal repro schema below. This query against the included schema causes the error:
```
{
  "measures": [
    "RC.resourceCount"
  ],
  "timeDimensions": [
    {
      "dimension": "RC.date",
      "granularity": "day",
      "dateRange": "Last 30 days"
    }
  ],
  "order": {
    "RC.resourceCount": "desc"
  },
  "dimensions": [
    "CS.resourceType",
    "D.name"
  ]
}
```
![image](https://user-images.githubusercontent.com/801183/233711639-24fc0cf0-f8d4-4fc6-a091-a0b1a8591094.png)

**Screenshots**
Here I've highlighted the queries so that it easy to see the mismatch in column names:
![image](https://user-images.githubusercontent.com/801183/233697069-be70bdf0-97b9-4f94-a3c3-e298d9185bcc.png)

**Minimally reproducible Cube Schema**

```javascript
cube(`RC`, {
  sql: `SELECT 'restype1' as resource_type, '2020-01-01'::date as date`,

  preAggregations: {
    byDashboard: {
      measures: [CUBE.resourceCount],
      dimensions: [CS.resourceType, D.name],
      timeDimension: CUBE.date,
      granularity: `day`,
    },
  },

  joins: {
    CS: {
      relationship: `hasMany`,
      sql: `${CUBE}.resource_type = ${CS.resourceType}`,
    },
  },

  measures: {
    resourceCount: {
      sql: `resource_count`,
      type: `sum`,
    },
  },

  dimensions: {
    resourceType: {
      sql: `resource_type`,
      type: `string`,
      primaryKey: true,
      shown: true,
    },

    date: {
      sql: `date`,
      type: `time`,
      primaryKey: true,
      shown: true,
    },
  },

  dataSource: `default`,
});

cube(`CS`, {
  sql: `SELECT 1 as id, 1 as control_id, 'restype1' as resource_type`,

  joins: {
    C: {
      sql: `${CUBE}.control_id = ${C.id}`,
      relationship: `belongsTo`,
    },
  },

  dimensions: {
    id: {
      sql: `id`,
      type: `number`,
      primaryKey: true,
    },

    controlId: {
      sql: `control_id`,
      type: `number`,
    },

    resourceType: {
      sql: `resource_type`,
      type: `string`,
    },
  },

  dataSource: `default`,
});

cube(`C`, {
  sql: `SELECT 1 as id`,

  joins: {
    DE: {
      sql: `${CUBE}.id = ${DE.controlId}`,
      relationship: `hasMany`,
    },
  },

  dimensions: {
    id: {
      sql: `id`,
      type: `number`,
      primaryKey: true,
    },
  },

  dataSource: `default`,
});

cube(`DE`, {
  sql: `SELECT 1 as id, 1 as dashboard_id, 1 as control_id`,

  joins: {
    D: {
      sql: `${CUBE}.dashboard_id = ${D.id}`,
      relationship: `belongsTo`,
    },
  },

  dimensions: {
    id: {
      sql: `id`,
      type: `number`,
      primaryKey: true,
    },

    dashboardId: {
      sql: `dashboard_id`,
      type: `number`,
    },

    controlId: {
      sql: `control_id`,
      type: `number`,
    },
  },

  dataSource: `default`,
});

cube(`D`, {
  sql: `SELECT 1 as id, 'Dashboard1' as name`,

  preAggregations: {
    resourceTypes: {
      dimensions: [CUBE.name, CS.resourceType],
    },
  },

  dimensions: {
    id: {
      sql: `id`,
      type: `number`,
      primaryKey: true,
    },

    name: {
      sql: `name`,
      type: `string`,
    },
  },

  dataSource: `default`,
});

```

**Version:**
Present in both 0.32.18 and 0.32.28

**Additional context**
Full error log:
```
Error while querying: scheduler-8373aa22-4636-498e-b86e-5e4ad016290b (151ms)
{
  "processingId": "81",
  "queueSize": 1,
  "queryKey": [
    [
      "CREATE TABLE dev_pre_aggregations.r_c_by_dashboard AS SELECT q_0.\"c_s__resource_type\", q_0.\"d__name\", q_0.\"r_c__date_day\", \"r_c__resource_count\" \"r_c__resource_count\" FROM (SELECT \"keys\".\"c_s__resource_type\", \"keys\".\"d__name\", \"keys\".\"r_c__date_day\", sum(\"r_c_key__r_c\".resource_count) \"r_c__resource_count\" FROM (SELECT DISTINCT \"r_c_key__c_s\".resource_type \"c_s__resource_type\", \"r_c_key__d\".name \"d__name\", date_trunc('day', (\"r_c_key__r_c\".date::timestamptz AT TIME ZONE 'UTC')) \"r_c__date_day\", \"r_c_key__r_c\".resource_type \"r_c__resource_type\" FROM (SELECT 'restype1' as resource_type, '2020-01-01'::date as date) AS \"r_c_key__r_c\"\nLEFT JOIN (SELECT 1 as id, 1 as control_id, 'restype1' as resource_type) AS \"r_c_key__c_s\" ON \"r_c_key__r_c\".resource_type = \"r_c_key__c_s\".resource_type\nLEFT JOIN (SELECT 1 as id) AS \"r_c_key__c\" ON \"r_c_key__c_s\".control_id = \"r_c_key__c\".id\nLEFT JOIN (SELECT 1 as id, 1 as dashboard_id, 1 as control_id) AS \"r_c_key__d_e\" ON \"r_c_key__c\".id = \"r_c_key__d_e\".control_id\nLEFT JOIN (SELECT 1 as id, 'Dashboard1' as name) AS \"r_c_key__d\" ON \"r_c_key__d_e\".dashboard_id = \"r_c_key__d\".id ) AS \"keys\"\nLEFT JOIN (SELECT 'restype1' as resource_type, '2020-01-01'::date as date) AS \"r_c_key__r_c\" ON \"keys\".\"r_c__resource_type\" = \"r_c_key__r_c\".resource_type AND \"keys\".\"r_c__date\" = \"r_c_key__r_c\".date\n              GROUP BY 1, 2, 3) as q_0 ",
      []
    ],
    [
      [
        {
          "refresh_key": "467248"
        }
      ],
      [
        {
          "refresh_key": "467248"
        }
      ],
      [
        {
          "refresh_key": "467248"
        }
      ],
      [
        {
          "refresh_key": "467248"
        }
      ],
      [
        {
          "refresh_key": "467248"
        }
      ]
    ]
  ],
  "queuePrefix": "SQL_PRE_AGGREGATIONS_STANDALONE_default",
  "timeInQueue": 5,
  "preAggregationId": "RC.byDashboard",
  "newVersionEntry": {
    "table_name": "dev_pre_aggregations.r_c_by_dashboard",
    "structure_version": "rz51wxpt",
    "content_version": "rliek4x5",
    "last_updated_at": 1682096336169,
    "naming_version": 2
  },
  "preAggregation": {
    "preAggregationId": "RC.byDashboard",
    "timezone": "UTC",
    "timestampFormat": "YYYY-MM-DD[T]HH:mm:ss.SSS[Z]",
    "tableName": "dev_pre_aggregations.r_c_by_dashboard",
    "invalidateKeyQueries": [
      [
        "SELECT FLOOR((UNIX_TIMESTAMP()) / 3600) as refresh_key",
        [],
        {
          "external": true,
          "renewalThreshold": 10
        }
      ],
      [
        "SELECT FLOOR((UNIX_TIMESTAMP()) / 3600) as refresh_key",
        [],
        {
          "external": true,
          "renewalThreshold": 10
        }
      ],
      [
        "SELECT FLOOR((UNIX_TIMESTAMP()) / 3600) as refresh_key",
        [],
        {
          "external": true,
          "renewalThreshold": 10
        }
      ],
      [
        "SELECT FLOOR((UNIX_TIMESTAMP()) / 3600) as refresh_key",
        [],
        {
          "external": true,
          "renewalThreshold": 10
        }
      ],
      [
        "SELECT FLOOR((UNIX_TIMESTAMP()) / 3600) as refresh_key",
        [],
        {
          "external": true,
          "renewalThreshold": 10
        }
      ]
    ],
    "type": "rollup",
    "external": true,
    "previewSql": [
      "SELECT * FROM dev_pre_aggregations.r_c_by_dashboard LIMIT 1000",
      []
    ],
    "preAggregationsSchema": "dev_pre_aggregations",
    "loadSql": [
      "CREATE TABLE dev_pre_aggregations.r_c_by_dashboard AS SELECT q_0.\"c_s__resource_type\", q_0.\"d__name\", q_0.\"r_c__date_day\", \"r_c__resource_count\" \"r_c__resource_count\" FROM (SELECT \"keys\".\"c_s__resource_type\", \"keys\".\"d__name\", \"keys\".\"r_c__date_day\", sum(\"r_c_key__r_c\".resource_count) \"r_c__resource_count\" FROM (SELECT DISTINCT \"r_c_key__c_s\".resource_type \"c_s__resource_type\", \"r_c_key__d\".name \"d__name\", date_trunc('day', (\"r_c_key__r_c\".date::timestamptz AT TIME ZONE 'UTC')) \"r_c__date_day\", \"r_c_key__r_c\".resource_type \"r_c__resource_type\" FROM (SELECT 'restype1' as resource_type, '2020-01-01'::date as date) AS \"r_c_key__r_c\"\nLEFT JOIN (SELECT 1 as id, 1 as control_id, 'restype1' as resource_type) AS \"r_c_key__c_s\" ON \"r_c_key__r_c\".resource_type = \"r_c_key__c_s\".resource_type\nLEFT JOIN (SELECT 1 as id) AS \"r_c_key__c\" ON \"r_c_key__c_s\".control_id = \"r_c_key__c\".id\nLEFT JOIN (SELECT 1 as id, 1 as dashboard_id, 1 as control_id) AS \"r_c_key__d_e\" ON \"r_c_key__c\".id = \"r_c_key__d_e\".control_id\nLEFT JOIN (SELECT 1 as id, 'Dashboard1' as name) AS \"r_c_key__d\" ON \"r_c_key__d_e\".dashboard_id = \"r_c_key__d\".id ) AS \"keys\"\nLEFT JOIN (SELECT 'restype1' as resource_type, '2020-01-01'::date as date) AS \"r_c_key__r_c\" ON \"keys\".\"r_c__resource_type\" = \"r_c_key__r_c\".resource_type AND \"keys\".\"r_c__date\" = \"r_c_key__r_c\".date\n              GROUP BY 1, 2, 3) as q_0 ",
      []
    ],
    "sql": [
      "SELECT q_0.\"c_s__resource_type\", q_0.\"d__name\", q_0.\"r_c__date_day\", \"r_c__resource_count\" \"r_c__resource_count\" FROM (SELECT \"keys\".\"c_s__resource_type\", \"keys\".\"d__name\", \"keys\".\"r_c__date_day\", sum(\"r_c_key__r_c\".resource_count) \"r_c__resource_count\" FROM (SELECT DISTINCT \"r_c_key__c_s\".resource_type \"c_s__resource_type\", \"r_c_key__d\".name \"d__name\", date_trunc('day', (\"r_c_key__r_c\".date::timestamptz AT TIME ZONE 'UTC')) \"r_c__date_day\", \"r_c_key__r_c\".resource_type \"r_c__resource_type\" FROM (SELECT 'restype1' as resource_type, '2020-01-01'::date as date) AS \"r_c_key__r_c\"\nLEFT JOIN (SELECT 1 as id, 1 as control_id, 'restype1' as resource_type) AS \"r_c_key__c_s\" ON \"r_c_key__r_c\".resource_type = \"r_c_key__c_s\".resource_type\nLEFT JOIN (SELECT 1 as id) AS \"r_c_key__c\" ON \"r_c_key__c_s\".control_id = \"r_c_key__c\".id\nLEFT JOIN (SELECT 1 as id, 1 as dashboard_id, 1 as control_id) AS \"r_c_key__d_e\" ON \"r_c_key__c\".id = \"r_c_key__d_e\".control_id\nLEFT JOIN (SELECT 1 as id, 'Dashboard1' as name) AS \"r_c_key__d\" ON \"r_c_key__d_e\".dashboard_id = \"r_c_key__d\".id ) AS \"keys\"\nLEFT JOIN (SELECT 'restype1' as resource_type, '2020-01-01'::date as date) AS \"r_c_key__r_c\" ON \"keys\".\"r_c__resource_type\" = \"r_c_key__r_c\".resource_type AND \"keys\".\"r_c__date\" = \"r_c_key__r_c\".date\n              GROUP BY 1, 2, 3) as q_0 ",
      []
    ],
    "uniqueKeyColumns": [
      "\"c_s__resource_type\"",
      "\"d__name\"",
      "\"r_c__date_day\""
    ],
    "aggregationsColumns": [
      "sum(\"r_c__resource_count\")"
    ],
    "dataSource": "default",
    "granularity": "day",
    "preAggregationStartEndQueries": [
      [
        "select min((\"r_c\".date::timestamptz AT TIME ZONE 'UTC')) from (SELECT 'restype1' as resource_type, '2020-01-01'::date as date) AS \"r_c\"",
        []
      ],
      [
        "select max((\"r_c\".date::timestamptz AT TIME ZONE 'UTC')) from (SELECT 'restype1' as resource_type, '2020-01-01'::date as date) AS \"r_c\"",
        []
      ]
    ],
    "indexesSql": [],
    "createTableIndexes": [],
    "readOnly": false,
    "expandedPartition": true,
    "priority": -1
  },
  "addedToQueueTime": 1682096336170
} 
error: column keys.r_c__date does not exist
    at Parser.parseErrorMessage (/cube/node_modules/pg-protocol/src/parser.ts:369:69)
    at Parser.handlePacket (/cube/node_modules/pg-protocol/src/parser.ts:188:21)
    at Parser.parse (/cube/node_modules/pg-protocol/src/parser.ts:103:30)
    at Socket.<anonymous> (/cube/node_modules/pg-protocol/src/index.ts:7:48)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
Error querying db: scheduler-8373aa22-4636-498e-b86e-5e4ad016290b 
{} 
Error: column keys.r_c__date does not exist
    at QueryQueue.parseResult (/cube/node_modules/@cubejs-backend/query-orchestrator/src/orchestrator/QueryQueue.js:434:13)
    at QueryQueue.executeQueryInQueue (/cube/node_modules/@cubejs-backend/query-orchestrator/src/orchestrator/QueryQueue.js:411:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at PreAggregationLoader.loadPreAggregationWithKeys (/cube/node_modules/@cubejs-backend/query-orchestrator/src/orchestrator/PreAggregations.ts:790:7)
    at PreAggregationLoader.loadPreAggregation (/cube/node_modules/@cubejs-backend/query-orchestrator/src/orchestrator/PreAggregations.ts:573:22)
    at preAggregationPromise (/cube/node_modules/@cubejs-backend/query-orchestrator/src/orchestrator/PreAggregations.ts:2149:30)
    at QueryOrchestrator.fetchQuery (/cube/node_modules/@cubejs-backend/query-orchestrator/src/orchestrator/QueryOrchestrator.ts:241:9)
    at OrchestratorApi.executeQuery (/cube/node_modules/@cubejs-backend/server-core/src/core/OrchestratorApi.ts:98:20)
    at /cube/node_modules/@cubejs-backend/server-core/src/core/RefreshScheduler.ts:602:13
    at async Promise.all (index 0)
    at RefreshScheduler.refreshPreAggregations (/cube/node_modules/@cubejs-backend/server-core/src/core/RefreshScheduler.ts:587:5)
    at async Promise.all (index 1)
    at RefreshScheduler.runScheduledRefresh (/cube/node_modules/@cubejs-backend/server-core/src/core/RefreshScheduler.ts:285:9)
Refresh Scheduler Error: scheduler-8373aa22-4636-498e-b86e-5e4ad016290b 
{
  "securityContext": {}
} 
Error: column keys.r_c__date does not exist
```

Formatted queries from the error log:
```sql
CREATE TABLE DEV_PRE_AGGREGATIONS.R_C_BY_DASHBOARD AS
SELECT Q_0."c_s__resource_type",
	Q_0."d__name",
	Q_0."r_c__date_day",
	"r_c__resource_count" "r_c__resource_count"
FROM
	(SELECT "keys"."c_s__resource_type",
			"keys"."d__name",
			"keys"."r_c__date_day",
			SUM("r_c_key__r_c".RESOURCE_COUNT) "r_c__resource_count"
		FROM
			(SELECT DISTINCT "r_c_key__c_s".RESOURCE_TYPE "c_s__resource_type",
					"r_c_key__d".NAME "d__name",
					DATE_TRUNC('day', ("r_c_key__r_c".DATE::TIMESTAMPTZ AT TIME ZONE 'UTC')) "r_c__date_day",
					"r_c_key__r_c".RESOURCE_TYPE "r_c__resource_type"
				FROM
					(SELECT 'restype1' AS RESOURCE_TYPE,
							'2020-01-01'::date AS date) AS "r_c_key__r_c"
				LEFT JOIN
					(SELECT 1 AS ID,
							1 AS CONTROL_ID,
							'restype1' AS RESOURCE_TYPE) AS "r_c_key__c_s" ON "r_c_key__r_c".RESOURCE_TYPE = "r_c_key__c_s".RESOURCE_TYPE
				LEFT JOIN
					(SELECT 1 AS ID) AS "r_c_key__c" ON "r_c_key__c_s".CONTROL_ID = "r_c_key__c".ID
				LEFT JOIN
					(SELECT 1 AS ID,
							1 AS DASHBOARD_ID,
							1 AS CONTROL_ID) AS "r_c_key__d_e" ON "r_c_key__c".ID = "r_c_key__d_e".CONTROL_ID
				LEFT JOIN
					(SELECT 1 AS ID,
							'Dashboard1' AS NAME) AS "r_c_key__d" ON "r_c_key__d_e".DASHBOARD_ID = "r_c_key__d".ID) AS "keys"
		LEFT JOIN
			(SELECT 'restype1' AS RESOURCE_TYPE,
					'2020-01-01'::date AS date) AS "r_c_key__r_c" ON "keys"."r_c__resource_type" = "r_c_key__r_c".RESOURCE_TYPE
		AND "keys"."r_c__date" = "r_c_key__r_c".DATE
		GROUP BY 1, 2,
			3) AS Q_0
            
            
SELECT Q_0."c_s__resource_type",
	Q_0."d__name",
	Q_0."r_c__date_day",
	"r_c__resource_count" "r_c__resource_count"
FROM
	(SELECT "keys"."c_s__resource_type",
			"keys"."d__name",
			"keys"."r_c__date_day",
			SUM("r_c_key__r_c".RESOURCE_COUNT) "r_c__resource_count"
		FROM
			(SELECT DISTINCT "r_c_key__c_s".RESOURCE_TYPE "c_s__resource_type",
					"r_c_key__d".NAME "d__name",
					DATE_TRUNC('day', ("r_c_key__r_c".DATE::TIMESTAMPTZ AT TIME ZONE 'UTC')) "r_c__date_day",
					"r_c_key__r_c".RESOURCE_TYPE "r_c__resource_type"
				FROM
					(SELECT 'restype1' AS RESOURCE_TYPE,
							'2020-01-01'::date AS date) AS "r_c_key__r_c"
				LEFT JOIN
					(SELECT 1 AS ID,
							1 AS CONTROL_ID,
							'restype1' AS RESOURCE_TYPE) AS "r_c_key__c_s" ON "r_c_key__r_c".RESOURCE_TYPE = "r_c_key__c_s".RESOURCE_TYPE
				LEFT JOIN
					(SELECT 1 AS ID) AS "r_c_key__c" ON "r_c_key__c_s".CONTROL_ID = "r_c_key__c".ID
				LEFT JOIN
					(SELECT 1 AS ID,
							1 AS DASHBOARD_ID,
							1 AS CONTROL_ID) AS "r_c_key__d_e" ON "r_c_key__c".ID = "r_c_key__d_e".CONTROL_ID
				LEFT JOIN
					(SELECT 1 AS ID,
							'Dashboard1' AS NAME) AS "r_c_key__d" ON "r_c_key__d_e".DASHBOARD_ID = "r_c_key__d".ID) AS "keys"
		LEFT JOIN
			(SELECT 'restype1' AS RESOURCE_TYPE,
					'2020-01-01'::date AS date) AS "r_c_key__r_c" ON "keys"."r_c__resource_type" = "r_c_key__r_c".RESOURCE_TYPE
		AND "keys"."r_c__date" = "r_c_key__r_c".DATE
		GROUP BY 1, 2,
			3) AS Q_0
```

Thanks for looking!

**Comment by pacofvf** [comment]
The issue has to do with time dimensions used as one of the multiple primary keys. A workaround is to introduce a new artificial primary key e.g.
```
   id: {
      sql: `${CUBE}.resource_type || '_' || ${CUBE}.date`,
      type: `string`,
      primaryKey: true,
      shown: true,
    },
```

**Comment by tvansteenburgh** [comment]
Thanks @pacofvf, that got me unblocked!
