### ISSUE TITLE
Unable to load @cubejs-backend/native

### ISSUE THREAD

**Issue by victorvuelma** [cube-js/cube#6510]
**Describe the bug**
After trying to upgrade CubeJS versions from 0.31 to latest of 0.32, we are unable to start CubeJS on development mode.
After cube development environment initialization, runs a crash due to Native load fails.
I'm using Yarn v1 as package manager, Node JS 16.15 on a MacBook with M1 CPU.

**Logs**
```
🔓 Authentication checks are disabled in developer mode. Please use NODE_ENV=production to enable it.
🦅 Dev environment available at http://localhost:4000
⚠️  Your pre-aggregations will be on an external database. It is recommended to use Cube Store for optimal performance
Fatal error during server start: 
Error: Unable to load @cubejs-backend/native, probably your system (arm64-darwin) with Node.js v16.15.0 is not supported.
```

**To Reproduce**
1. Upgrade all CubeJS packages to v0.32.29
2. Try to run CubeJS using 'yarn cubejs-server'
3. Cube Will fail on server start, due to @cubejs-backend/native load fails

**Version:**
0.32.29

**Comment by alanreid** [comment]
Hi there! 

I managed to make it work by manually building the rust bindings. 

I was experiencing the same issue with `0.33.11` (and any other version I tried as well), while trying to run the dev server on a Macbook (M1 Max) directly. 

Steps to reproduce:

```bash
npm install -g cubejs-cli
cubejs create hello-world -d athena -t serverless
cd hello-world
npm run dev
```

Output:
```
> cubejs-dev-server

🔥 Cube Store (0.33.12) is assigned to 3030 port.
🔓 Authentication checks are disabled in developer mode. Please use NODE_ENV=production to enable it.
🦅 Dev environment available at http://localhost:4000

Fatal error during server start: 
Unable to load @cubejs-backend/native, probably your system (arm64-darwin) with Node.js v18.16.0 is not supported.
```

Since it's failing to download the bindings for `darwin-arm64` when installing the `@cubejs-backend/native` package:

``` 
GET https://github.com/cube-js/cube/releases/download/v0.33.11/native-darwin-arm64-unknown.tar.gz

ERR! install response status 404 Not Found on https://github.com/cube-js/cube/releases/download/v0.33.11/native-darwin-arm64-unknown.tar.gz 
```

I've manually built them:

```bash
git clone git@github.com:cube-js/cube.git
cd cube/packages/cubejs-backend-native

npm install   # This one will fail due to the error above, but ignore it
npm run native:build
npm run native:build-release
```

And copied the `cube/packages/cubejs-backend-native/index.node` file to the `node_modules/@cubejs-backend/native/native` in my project's folder.

A bit hacky, but hopefully it helps somebody else until this gets sorted :)

**Comment by ovr** [comment]
Hello!

Fixed & released. Should work starting from [https://github.com/cube-js/cube/releases/tag/v0.33.29](v0.33.29)

Thanks

**Comment by rahulrajpal2911** [comment]
Hi @ovr 
We encountered the same issue that @jove4015 faced a year ago. I attempted to downgrade the Cube.js version and upgrade the Node.js version. I tried both local installation and Docker, but neither method worked. Could you please help me?

![Cube error](https://github.com/cube-js/cube/assets/30856778/25d4f806-0162-4909-b128-16beb8638844)

`2024-06-17 13:01:18 🔥 Cube Store (0.35.48) is assigned to 3030 port.
2024-06-17 13:01:18 🔓 Authentication checks are disabled in developer mode. Please use NODE_ENV=production to enable it.
2024-06-17 13:01:18 🦅 Dev environment available at http://localhost:4000
2024-06-17 13:01:19 Fatal error during server start: 
2024-06-17 13:01:19 Error: Unable to load @cubejs-backend/native, probably your system (x64-linux) with Node.js v18.20.1 is not supported.
2024-06-17 13:01:19     at loadNative (/cube/conf/node_modules/@cubejs-backend/native/js/index.ts:111:9)
2024-06-17 13:01:19     at setupLogger (/cube/conf/node_modules/@cubejs-backend/native/js/index.ts:272:18)
2024-06-17 13:01:19     at new SQLServer (/cube/conf/node_modules/@cubejs-backend/api-gateway/src/sql-server.ts:32:16)
2024-06-17 13:01:19     at ApiGateway.initSQLServer (/cube/conf/node_modules/@cubejs-backend/api-gateway/src/gateway.ts:507:25)
2024-06-17 13:01:19     at CubejsServerCore.initSQLServer (/cube/conf/node_modules/@cubejs-backend/server-core/src/core/server.ts:429:23)
2024-06-17 13:01:19     at CubejsServer.listen (/cube/conf/node_modules/@cubejs-backend/server/src/server.ts:113:36)
2024-06-17 13:01:19     at ServerContainer.runServerInstance (/cube/conf/node_modules/@cubejs-backend/server/src/server/container.ts:241:35)
2024-06-17 13:01:19     at makeInstance (/cube/conf/node_modules/@cubejs-backend/server/src/server/container.ts:389:22)
2024-06-17 13:01:19     at ServerContainer.start (/cube/conf/node_modules/@cubejs-backend/server/src/server/container.ts:402:20)
2024-06-17 13:01:19     at Server.run (/cube/conf/node_modules/@cubejs-backend/server/src/command/server.ts:25:5)
2024-06-17 13:01:19     at Server._run (/cube/conf/node_modules/@oclif/command/lib/command.js:43:20)
2024-06-17 13:01:19     at Config.runCommand (/cube/conf/node_modules/@oclif/config/lib/config.js:173:24)
2024-06-17 13:01:19     at Main.run (/cube/conf/node_modules/@oclif/command/lib/main.js:28:9)
2024-06-17 13:01:19     at Main._run (/cube/conf/node_modules/@oclif/command/lib/command.js:43:20)`

**Comment by ovr** [comment]
@rahulrajpal2911

The 0.35.48 release was broken; I've re-released it. Should work now.

**Comment by rahulrajpal2911** [comment]
@ovr Thank you for the quick response. I updated it to 0.35.50 and did a fresh install after removing node_modules and package-lock but, still I'm getting the same error.

![image](https://github.com/cube-js/cube/assets/30856778/8973d190-7482-48f5-969c-eb487250f647)

**Comment by rahulrajpal2911** [comment]
@ovr It worked when I tried it again after deleting the node_modules folder and clearing the cache from npm. Thank you.

**Comment by DungVPH** [comment]
Warning. Unable to load native extension. You are using a Linux distro with Musl which is not supported. Read more: https://github.com/cube-js/cube/blob/master/packages/cubejs-backend-native/README.md#supported-architectures-and-platforms
Error: Unable to load @cubejs-backend/native, probably your system (x64-linux) with Node.js v20.18.1 is not supported.

**Comment by AwesomeBobX64** [comment]
It'd be nice to get a version that works in an Alpine image. Any idea if/when that will be the case?
