### ISSUE TITLE
[cubestore] panicking when executing a drop table using the mysql interface

### ISSUE THREAD

**Issue by lvauvillier** [cube-js/cube#6517]
**Describe the bug**

When you send a drop table command using the cubestore mysql interface:

```sql
drop table prod_pre_aggregations.events_dashboard20211126_suzbctmg_fbrc2rzm_1i44uod;
```

Error received:

```
thread 'cubestore-main' panicked at 'index out of bounds: the len is 1 but the index is 1', cubestore/src/sql/mod.rs:1166:67
stack backtrace:
   0: rust_begin_unwind
             at /rustc/dc80ca78b6ec2b6bba02560470347433bcd0bb3c/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/dc80ca78b6ec2b6bba02560470347433bcd0bb3c/library/core/src/panicking.rs:142:14
   2: core::panicking::panic_bounds_check
             at /rustc/dc80ca78b6ec2b6bba02560470347433bcd0bb3c/library/core/src/panicking.rs:84:5
   3: <cubestore::sql::SqlServiceImpl as cubestore::sql::SqlService>::exec_query_with_context::{{closure}}::{{closure}}
   4: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   5: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   6: msql_srv::AsyncMysqlIntermediary<B,R>::run_on::{{closure}}
   7: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   8: tokio::runtime::task::core::CoreStage<T>::poll
   9: tokio::runtime::task::harness::poll_future
  10: tokio::runtime::task::harness::Harness<T,S>::poll
  11: std::thread::local::LocalKey<T>::with
  12: tokio::runtime::thread_pool::worker::Context::run_task
  13: tokio::runtime::thread_pool::worker::Context::run
  14: tokio::macros::scoped_tls::ScopedKey<T>::set
  15: tokio::runtime::thread_pool::worker::run
  16: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
  17: tokio::runtime::task::harness::Harness<T,S>::poll
  18: tokio::runtime::blocking::pool::Inner::run
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by igorlukanin** [comment]
I have just checked and it looks like this has been fixed. Does not reproduce on Cube v0.36.x:

<img width="1018" alt="Screenshot 2024-10-09 at 01 08 51" src="https://github.com/user-attachments/assets/2369d26a-ca27-4c06-9d7e-9ca1af79676e">
