### ISSUE TITLE
YAMLException: bad indentation of a mapping entry

### ISSUE THREAD

**Issue by taitung** [cube-js/cube#6656]
**Describe the bug**
<img width="348" alt="Screenshot 2023-05-26 at 9 23 04 AM" src="https://github.com/cube-js/cube/assets/1073330/808b0fd9-65d0-45a2-ab1d-abd81bf52d93">

```
YAMLException: bad indentation of a mapping entry (3:16)

 1 | cubes:
 2 |   - name: c_a_m_p_a_i_g_n_emails
 3 |     sql_table: `ODS`.`CAMPAIGN_EMAILS`
--------------------^
 4 |     data_source: default
 5 | 

    at generateError (/cube/node_modules/js-yaml/lib/loader.js:183:10)
    at throwError (/cube/node_modules/js-yaml/lib/loader.js:187:9)
    at readBlockMapping (/cube/node_modules/js-yaml/lib/loader.js:1182:7)
    at composeNode (/cube/node_modules/js-yaml/lib/loader.js:1441:12)
    at readBlockSequence (/cube/node_modules/js-yaml/lib/loader.js:1008:5)
    at composeNode (/cube/node_modules/js-yaml/lib/loader.js:1440:12)
    at readBlockMapping (/cube/node_modules/js-yaml/lib/loader.js:1164:11)
    at composeNode (/cube/node_modules/js-yaml/lib/loader.js:1441:12)
    at readDocument (/cube/node_modules/js-yaml/lib/loader.js:1625:3)
    at loadDocuments (/cube/node_modules/js-yaml/lib/loader.js:1688:5)
    at Object.load (/cube/node_modules/js-yaml/lib/loader.js:1714:19)
    at YamlCompiler.compileYamlFile (/cube/node_modules/@cubejs-backend/schema-compiler/src/compiler/YamlCompiler.ts:36:26)
    at DataSchemaCompiler.compileFile (/cube/node_modules/@cubejs-backend/schema-compiler/src/compiler/DataSchemaCompiler.js:175:25)
    at /cube/node_modules/@cubejs-backend/schema-compiler/src/compiler/DataSchemaCompiler.js:144:14
    at Array.forEach (<anonymous>)
    at DataSchemaCompiler.compileCubeFiles (/cube/node_modules/@cubejs-backend/schema-compiler/src/compiler/DataSchemaCompiler.js:143:8)
    at compilePhase (/cube/node_modules/@cubejs-backend/schema-compiler/src/compiler/DataSchemaCompiler.js:61:50)
    at /cube/node_modules/@cubejs-backend/schema-compiler/src/compiler/DataSchemaCompiler.js:63:16
    at CompilerApi.getCompilers (/cube/node_modules/@cubejs-backend/server-core/src/core/CompilerApi.js:58:26)
    at CompilerApi.metaConfig (/cube/node_modules/@cubejs-backend/server-core/src/core/CompilerApi.js:203:13)
    at ApiGateway.meta (/cube/node_modules/@cubejs-backend/api-gateway/src/gateway.ts:510:26)
    at /cube/node_modules/@cubejs-backend/api-gateway/src/gateway.ts:315:11
```

**To Reproduce**
After selecting the `Data Model` tab on the playground, I ticked some tables and then clicked `Generate Data Model` to generate the models with `YAML` format.
 
<img width="340" alt="Screenshot 2023-05-26 at 9 17 20 AM" src="https://github.com/cube-js/cube/assets/1073330/7dd4059b-7a2c-47b1-beeb-c6c55ab25f1f">. Then I select the tab `Playground` and the error of bad indentation pops up. 

**workaround**
Add double quotes to the string of `sql_table`. For example,  \`sql_table\`: "\`ODS\`.\`CAMPAIGN_EMAILS\`"

**Comment by paveltiunov** [comment]
@taitung Thanks for posting this one! Was it generated this way?

**Comment by taitung** [comment]
The same error that is shown in the video was tested with version 0.33.15

https://github.com/cube-js/cube/assets/1073330/27e3ae80-02f8-4027-a330-e974dfdf62fb

**Comment by taitung** [comment]
@paveltiunov, sorry that I didn't mention the db I connected to. It is BigQuery

**Comment by igorlukanin** [comment]
I was able to reproduce this on the latest (v0.36.2) version of Cube, both in Cube Core and Cube Cloud.

It looks like Cube handles lowercase schema/table names just fine because it does not enclose them into quotes. However, in case of uppercase schema/table names, Cube encloses them in backticks and generates incorrect YAML:

<img width="1392" alt="Screenshot 2024-09-25 at 18 05 40" src="https://github.com/user-attachments/assets/0d696571-4490-4550-9126-97fc3dab4b42">

<img width="1392" alt="Screenshot 2024-09-25 at 18 05 53" src="https://github.com/user-attachments/assets/94ccd136-9a47-48c0-b5cb-07debad6f316">
