### ISSUE TITLE
ArangoDB driver is inoperable

### ISSUE THREAD

**Issue by tokarenko** [cube-js/cube#6896]
**Describe the bug**
ArangoDB driver is inoperable with the latest 0.30.39 version of Cube. Also tried with v0.30.0 from the last year when the driver was developed with the same result: "Unsupported db type: arangodb".
I understand that the driver is supported by community. I would be grateful if you could suggest how to fix the issue.
```
Error while loading DB schema
Error: Unsupported db type: arangodb
at Object.driverDependencies (/cube/node_modules/@cubejs-backend/server-core/src/core/DriverResolvers.ts:24:9)
at Object.lookupDriverClass (/cube/node_modules/@cubejs-backend/server-core/src/core/DriverResolvers.ts:36:5)
at Function.createDriver (/cube/node_modules/@cubejs-backend/server-core/src/core/DriverResolvers.ts:50:23)
at CubejsServerCore.resolveDriver (/cube/node_modules/@cubejs-backend/server-core/src/core/server.ts:750:28)
at processTicksAndRejections (internal/process/task_queues.js:95:5)
at CubejsServerCore.getDriver (/cube/node_modules/@cubejs-backend/server-core/src/core/server.ts:723:22)
at /cube/node_modules/@cubejs-backend/server-core/src/core/DevServer.ts:108:22
at /cube/node_modules/@cubejs-backend/server-core/src/core/DevServer.ts:78:9
```

**To Reproduce**
1. Run ghcr.io/panoti/cube:main docker image as described in https://github.com/panoti/cubejs-arangodb-driver#usage

**Expected behavior**
Driver loads without error.

**Version:**
0.30.39

**Comment by tokarenko** [comment]
The driver will be fixed by its author.
