### ISSUE TITLE
npm i @cubejs-backend/server@0.29.28 failed with 500

### ISSUE THREAD

**Issue by aliceliu0017** [cube-js/cube#7070]
**Problem**
I was using cube js in the internal system since 2021, but now that project can't be run locally. because I can't install @cubejs-backend/server@0.29.28

The error I got from npm i @cubejs-backend/server@0.29.28 is like below: 

```
npm ERR! RequestError [HttpError]: request to https://api.github.com/repos/cube-js/cube.js/releases/tags/v0.29.28 failed, reason: unable to get local issuer certificate
npm ERR!     at /Users/alice.liu/CodeSpace/scm-dashboard-backend/node_modules/@octokit/request/dist-src/fetch-wrapper.js:92:15
npm ERR!     at processTicksAndRejections (node:internal/process/task_queues:96:5)
npm ERR!     at fetchRelease (/Users/alice.liu/CodeSpace/scm-dashboard-backend/node_modules/@cubejs-backend/cubestore/js-wrapper/src/download.ts:26:20)
npm ERR!     at Object.downloadBinaryFromRelease (/Users/alice.liu/CodeSpace/scm-dashboard-backend/node_modules/@cubejs-backend/cubestore/js-wrapper/src/download.ts:63:19)
npm ERR!     at /Users/alice.liu/CodeSpace/scm-dashboard-backend/node_modules/@cubejs-backend/cubestore/js-wrapper/src/post-install.ts:12:7 {
npm ERR!   status: 500,
npm ERR!   request: {
npm ERR!     method: 'GET',
npm ERR!     url: 'https://api.github.com/repos/cube-js/cube.js/releases/tags/v0.29.28',
npm ERR!     headers: {
npm ERR!       accept: 'application/vnd.github.v3+json',
npm ERR!       'user-agent': 'octokit-core.js/3.5.1 Node.js/16.13.0 (darwin; arm64)'
npm ERR!     },
npm ERR!     request: { agent: undefined, hook: [Function: bound bound register] }
npm ERR!   }
npm ERR! }

```

Please let me know how should I interpret the message

**Comment by aliceliu0017** [comment]
@paveltiunov can you please help take a look? this issue blocks my work now. Thanks a million!

**Comment by paveltiunov** [comment]
@aliceliu0017 I guess you'd like to upgrade. It's been a while since you didn't.

**Comment by ovr** [comment]
> reason: unable to get local issuer certificate

To fix this error, you can try the following solutions:

- Update CA Certificates:

If you use Debian based distro, you can do the following:

```sh
sudo apt-get update
sudo apt --only-upgrade install ca-certificates
```

- Specify the CA Certificate: You can download and explicitly specify the CA certificate.
- Bypass SSL Verification (Not Recommended)
- Skip installation of Cube Store with `CUBESTORE_SKIP_POST_INSTALL=true`
