### ISSUE TITLE
Docker Debian Based Image add curl for health check

### ISSUE THREAD

**Issue by hannosgit** [cube-js/cube#7134]
**Is your feature request related to a problem? Please describe.**
To make our cube image (cubejs/cube) deployment production-ready, we want to configure a health check in docker compose. (https://docs.docker.com/compose/compose-file/compose-file-v3/#healthcheck). We do this normally by probing a REST endpoint. For cube, we planned to probe this endpoint: https://cube.dev/docs/reference/rest-api#readyz . But the debian based image does not have curl or wget installed, so we cannot do this.

**Describe the solution you'd like**
Add curl or wget or any http client library to the image, so that we can use it to implement a health check.
If there is another possibility to implement a health check for docker compose, it would be nice to include it in the docs.

**Describe alternatives you've considered**
The alpine version of the prebuilt docker image has wget installed, but we want to avoid alpine images.

**Comment by igorlukanin** [comment]
@hannosgit Thanks for posting this! have you considered building your own extended image based on the official one?

Also, I wonder why Alpine is not on option here.

**Comment by hannosgit** [comment]
I found a work around for the debian based image:
```
healthcheck:
      test: bash -c ':> /dev/tcp/127.0.0.1/4000' || exit 1
      ...
```
@igorlukanin when using the alpine version, a warning is displayed. I dont know the consequences of this warning...

```
Warning. Unable to load native extension. You are using a Linux distro with Musl which is not supported. Read more: https://github.com/cube-js/cube/blob/master/packages/cubejs-backend-native/README.md#supported-architectures-and-platforms
```
On some machines cube cannot even start with the alpine version:

```
Fatal error during server start:
Error: Unable to load @cubejs-backend/native, probably your system (x64-linux) with Node.js v16.20.2 is not supported.
    at loadNative (/cube/node_modules/@cubejs-backend/native/js/index.ts:90:9)
    at setupLogger (/cube/node_modules/@cubejs-backend/native/js/index.ts:249:18)
    at new SQLServer (/cube/node_modules/@cubejs-backend/api-gateway/src/sql-server.ts:31:16)
    at ApiGateway.initSQLServer (/cube/node_modules/@cubejs-backend/api-gateway/src/gateway.ts:462:12)
    at CubejsServerCore.initSQLServer (/cube/node_modules/@cubejs-backend/server-core/src/core/server.ts:430:23)
    at CubejsServer.listen (/cube/node_modules/@cubejs-backend/server/src/server.ts:120:36)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at ServerContainer.runServerInstance (/cube/node_modules/@cubejs-backend/server/src/server/container.ts:241:35)
    at makeInstance (/cube/node_modules/@cubejs-backend/server/src/server/container.ts:393:22)
    at ServerContainer.start (/cube/node_modules/@cubejs-backend/server/src/server/container.ts:406:20)
    at Server.run (/cube/node_modules/@cubejs-backend/server/src/command/server.ts:25:5)
    at Command.<anonymous> (/cube/node_modules/cubejs-cli/src/command/proxy-command.ts:51:13)
```
