### ISSUE TITLE
Error: Socket hang up

### ISSUE THREAD

**Issue by timurkhakhalev** [cube-js/cube#7169]
**Problem**

Hi! I have app with Cube.js version 0.33.58 and ClickHouse 23 with two environments, production and development. Recently I faced with an error when I try to query at production env:

```
Dropping Cache: e7d389bd-b74e-484e-aa27-046cb355cfa9-span-1

Error: socket hang up
    at QueryQueue.parseResult (/app/client/node_modules/@cubejs-backend/query-orchestrator/src/orchestrator/QueryQueue.js:368:13)
    at QueryQueue.executeInQueue (/app/client/node_modules/@cubejs-backend/query-orchestrator/src/orchestrator/QueryQueue.js:340:19)
    at /app/client/node_modules/@cubejs-backend/query-orchestrator/src/orchestrator/QueryCache.ts:745:17
    at QueryOrchestrator.fetchQuery (/app/client/node_modules/@cubejs-backend/query-orchestrator/src/orchestrator/QueryOrchestrator.ts:302:20)
    at OrchestratorApi.executeQuery (/app/client/node_modules/@cubejs-backend/server-core/src/core/OrchestratorApi.ts:98:20)
    at /app/client/node_modules/@cubejs-backend/api-gateway/src/gateway.ts:1434:21
    at async Promise.all (index 0)
    at ApiGateway.getSqlResponseInternal (/app/client/node_modules/@cubejs-backend/api-gateway/src/gateway.ts:1432:31)
    at /app/client/node_modules/@cubejs-backend/api-gateway/src/gateway.ts:1610:28
    at async Promise.all (index 0)
Dropping Cache: e7d389bd-b74e-484e-aa27-046cb355cfa9-span-1

Error: socket hang up
    at QueryQueue.parseResult (/app/client/node_modules/@cubejs-backend/query-orchestrator/src/orchestrator/QueryQueue.js:368:13)
    at QueryQueue.executeInQueue (/app/client/node_modules/@cubejs-backend/query-orchestrator/src/orchestrator/QueryQueue.js:340:19)
    at /app/client/node_modules/@cubejs-backend/query-orchestrator/src/orchestrator/QueryCache.ts:745:17
Error while renew cycle: e7d389bd-b74e-484e-aa27-046cb355cfa9-span-1
--

Error: socket hang up
    at QueryQueue.parseResult (/app/client/node_modules/@cubejs-backend/query-orchestrator/src/orchestrator/QueryQueue.js:368:13)
    at QueryQueue.executeInQueue (/app/client/node_modules/@cubejs-backend/query-orchestrator/src/orchestrator/QueryQueue.js:340:19)
    at /app/client/node_modules/@cubejs-backend/query-orchestrator/src/orchestrator/QueryCache.ts:745:17
Error querying db: e7d389bd-b74e-484e-aa27-046cb355cfa9-span-1
--

Error: socket hang up
    at QueryQueue.parseResult (/app/client/node_modules/@cubejs-backend/query-orchestrator/src/orchestrator/QueryQueue.js:368:13)
    at QueryQueue.executeInQueue (/app/client/node_modules/@cubejs-backend/query-orchestrator/src/orchestrator/QueryQueue.js:340:19)
    at /app/client/node_modules/@cubejs-backend/query-orchestrator/src/orchestrator/QueryCache.ts:745:17
    at QueryOrchestrator.fetchQuery (/app/client/node_modules/@cubejs-backend/query-orchestrator/src/orchestrator/QueryOrchestrator.ts:302:20)
    at OrchestratorApi.executeQuery (/app/client/node_modules/@cubejs-backend/server-core/src/core/OrchestratorApi.ts:98:20)
    at /app/client/node_modules/@cubejs-backend/api-gateway/src/gateway.ts:1434:21
    at async Promise.all (index 0)
    at ApiGateway.getSqlResponseInternal (/app/client/node_modules/@cubejs-backend/api-gateway/src/gateway.ts:1432:31)
    at /app/client/node_modules/@cubejs-backend/api-gateway/src/gateway.ts:1610:28
    at async Promise.all (index 0)
```

Also there are no related logs at  /var/log/clickhouse-server/clickhouse-server.log and  /var/log/clickhouse-server/clickhouse-server.err.log

But at development environment query is ok. Also when I try to start this query in Clickhouse native client on server its work good too.

Is it possible to get more details about this error?

**Comment by paveltiunov** [comment]
@timurkhakhalev You should check if your clickhouse restarts.

**Comment by timurkhakhalev** [comment]
> @timurkhakhalev You should check if your clickhouse restarts.

No its not. I checked it via this function https://clickhouse.com/docs/en/sql-reference/functions/other-functions#uptime

**Comment by timurkhakhalev** [comment]
Btw yesterday we discuss at [Slack](https://cube-js.slack.com/archives/C04NYBJP7RQ/p1695810098104639) with Igor Lukanin about this failure and I has concluded that error "socket hang up" maybe related with 5 sec timeout. Any thoughts?

**Comment by paveltiunov** [comment]
@timurkhakhalev It's misconfiguration on the Clickhouse side. There's no such setting on Cube side.
