### ISSUE TITLE
v0.34.7 breaks cross-OS installation

### ISSUE THREAD

**Issue by eugene1g** [cube-js/cube#7291]
**Describe the bug**
Up to and including `v0.34.6`, I was able to install the library on a Mac and deploy the same `node_modules` folder to a Linux server. Starting with `v0.34.7` I get a new error:

```
 Error: /data/www/xxxxxxxxxxx/node_modules/@cubejs-backend/native/native/index.node: invalid ELF header
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1327:18)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Function.Module._load (node:internal/modules/cjs/loader:938:12)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
    at require (node:internal/modules/helpers:130:18)
    at loadNative (/data/www/xxxxxxxxxxx/node_modules/@cubejs-backend/native/js/index.ts:87:12)
    at NativeInstance.getNative (/data/www/xxxxxxxxxxx/backend/node_modules/@cubejs-backend/native/js/index.ts:384:21)
    at NativeInstance.newJinjaEngine (/data/www/xxxxxxxxxxx/node_modules/@cubejs-backend/native/js/index.ts:390:19)
    at YamlCompiler.initFromPythonContext (/data/www/xxxxxxxxxxx/node_modules/@cubejs-backend/schema-compiler/src/compiler/YamlCompiler.ts:53:44)
    at DataSchemaCompiler.doCompile (/data/www/xxxxxxxxxxx/node_modules/@cubejs-backend/schema-compiler/src/compiler/DataSchemaCompiler.js:84:23)
    at CompilerApi.getCompilers (/data/www/xxxxxxxxxxx/node_modules/@cubejs-backend/server-core/src/core/CompilerApi.js:66:26)
    at CompilerApi.metaConfig (/data/www/xxxxxxxxxxx/node_modules/@cubejs-backend/server-core/src/core/CompilerApi.js:217:13)
    at ApiGateway.load (/data/www/xxxxxxxxxxx/node_modules/@cubejs-backend/api-gateway/src/gateway.ts:1589:30)
```

**To Reproduce**
1. Install on a Mac
2. Copy the same `node_modules` to a Linux server
3. Try to run execute any query

**Expected behavior**
I should be able to install the cube module on a Mac and deploy the same `node_modules` to Linux

**Screenshots**
(not applicable)

**Minimally reproducible Cube Schema**
(not applicable)

**Version:**
Cube `0.34.7` Node `20.8.1`

**Additional context**
(none)

**Comment by paveltiunov** [comment]
@eugene1g I guess we were never supporting this as it doesn't work in general for Node. Cube has native dependencies and those should be installed for every OS separately. If you want a portable image please use docker instead.

**Comment by eugene1g** [comment]
Ok, so the fact that this _was_  possible to do with `v0.34.6` and earlier was a happy coincidence but not something that Cube.js promised, so it's not a bug when that stops working. Got it.
