### ISSUE TITLE
How to configure jest environement to run cubejs queries from test ?

### ISSUE THREAD

**Issue by maximeoger** [cube-js/cube#7442]
**Problem**

I'm trying to implement intregration testing on a react component that uses the QueryBuilder to perform request to our cubejs backend. 

This is the first part of our application in which we will implement testing and we dont want to trigger real api call to our cubejs backend so we implemented a MSW solution to mock api calls to /meta. 

For the testing environement part, we use jsdom in our jest config (wich i think might cause the error that you will see below)

```shell
metaError: Error: Error
          at _callee$ (/Users/matthieu/dev/stash-app/node_modules/@cubejs-client/react/src/QueryBuilder.jsx:184:32)
          at tryCatch (/Users/matthieu/dev/stash-app/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:45:16)
          at Generator.<anonymous> (/Users/matthieu/dev/stash-app/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:133:17)
          at Generator.throw (/Users/matthieu/dev/stash-app/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:74:21)
          at asyncGeneratorStep (/Users/matthieu/dev/stash-app/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
          at _throw (/Users/matthieu/dev/stash-app/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
          at processTicksAndRejections (node:internal/process/task_queues:95:5),
      richMetaError: RequestError:
          at _callee5$ (/Users/matthieu/dev/stash-app/node_modules/@cubejs-client/core/src/index.js:165:23)
          at tryCatch (/Users/matthieu/dev/stash-app/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:45:16)
          at Generator.<anonymous> (/Users/matthieu/dev/stash-app/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:133:17)
          at Generator.next (/Users/matthieu/dev/stash-app/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:74:21)
          at asyncGeneratorStep (/Users/matthieu/dev/stash-app/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
          at _next (/Users/matthieu/dev/stash-app/node_modules/@babel/runtime/helpers/asyncToGenerator.js:22:9)
          at processTicksAndRejections (node:internal/process/task_queues:95:5) {
        response: { error: '' },
        status: undefined
      },
```

Apparently there is some issue in the CubeJsApi instance when he tries to reach the meta object and i think i might come from the testing environnement. We run the test in a jest environement wich is nodejs, simulate the dom with jsdom and use the undici package as polyfill for fetch, Headers, FormData, Request, Response objects 

Is there some correct way to setup jest environnement for integration testing components with QueryBuilder ?

Thanks for you help 

```
//jest.polyfills.js
const { TextDecoder, TextEncoder } = require('node:util')

Object.defineProperties(globalThis, {
    TextDecoder: { value: TextDecoder },
    TextEncoder: { value: TextEncoder },
})

const { Blob, File } = require('node:buffer')
const { fetch, Headers, FormData, Request, Response } = require('undici')

Object.defineProperties(globalThis, {
    fetch: { value: fetch, writable: true },
    Blob: { value: Blob },
    File: { value: File },
    Headers: { value: Headers },
    FormData: { value: FormData },
    Request: { value: Request },
    Response: { value: Response },
});

```

```
// jest.config.js
const nextJest = require("next/jest");

const createJestConfig = nextJest({
  dir: "./",
});

const customJestConfig = {
  setupFiles: [
    "<rootDir>/jest.polyfills.js",
  ],
  setupFilesAfterEnv: [
      "<rootDir>/jest.setup.js",
      "<rootDir>/test-utils/mocks/index.ts"
  ],
  moduleNameMapper: {
    "^@/components/(.*)$": "<rootDir>/components/$1",
    "^domains/(.*)$": "<rootDir>/domains/$1",
    "^store/(.*)$": "<rootDir>/store/$1",
    "^test-utils/(.*)$": "<rootDir>/test-utils/$1",
    "uuid": require.resolve('uuid'),
  },
  modulePathIgnorePatterns: [
    "<rootDir>/e2e-test-utils/",
    "<rootDir>/__tests__/",
  ],
  testPathIgnorePatterns: [
      "<rootDir>[/\\\\\\\\](node_modules|.next)[/\\\\\\\\]"
  ],
  transformIgnorePatterns: [
    "[/\\\\]node_modules[/\\\\].+\\.(ts|tsx)$",
  ],
  transform: {
    '^.+\\.(ts|tsx)$': 'babel-jest',
  },
  watchPlugins: [
    'jest-watch-typeahead/filename',
    'jest-watch-typeahead/testname',
  ],
  testEnvironment: "jsdom",
  testEnvironmentOptions: {
    customExportConditions: ['']
  },
  type: "module",
  preset: "ts-jest"
};

module.exports = createJestConfig(customJestConfig);
```

```
// jest.setup.js
import "@testing-library/jest-dom/extend-expect";
import next from "next";
import { worker } from "./test-utils/httpServer";

beforeAll(() => worker.listen({ onUnhandledRequest: 'warn' }));

afterEach(() => worker.resetHandlers());

afterAll(() => worker.close());

next({});
```

**Comment by benswinburne** [comment]
@maximeoger Did you ever get anywhere with this? Just attempted this in vitest and got the same problem
