### ISSUE TITLE
Unable to load @cubejs-backend/native on alpine images

### ISSUE THREAD

**Issue by anna-poz** [cube-js/cube#7869]
**Describe the bug**
When using `alpine` Docker images, cube fails to start up properly. The error with the stack trace is below:

```
"Error: Unable to load @cubejs-backend/native, probably your system (x64-linux) with Node.js v16.20.2 is not supported.
    at loadNative (/cube/node_modules/@cubejs-backend/native/js/index.ts:110:9)
    at NativeInstance.getNative (/cube/node_modules/@cubejs-backend/native/js/index.ts:416:19)
    at NativeInstance.newJinjaEngine (/cube/node_modules/@cubejs-backend/native/js/index.ts:422:17)
    at YamlCompiler.initFromPythonContext (/cube/node_modules/@cubejs-backend/schema-compiler/src/compiler/YamlCompiler.ts:48:44)
    at DataSchemaCompiler.doCompile (/cube/node_modules/@cubejs-backend/schema-compiler/src/compiler/DataSchemaCompiler.js:84:23)
    at CompilerApi.getCompilers (/cube/node_modules/@cubejs-backend/server-core/src/core/CompilerApi.js:67:26)
    at CompilerApi.metaConfig (/cube/node_modules/@cubejs-backend/server-core/src/core/CompilerApi.js:221:23)
    at ApiGateway.load (/cube/node_modules/@cubejs-backend/api-gateway/src/gateway.ts:1600:30)
    at /cube/node_modules/@cubejs-backend/api-gateway/src/gateway.ts:248:7"
message: "Compiling schema error"
```

**To Reproduce**
1. Update from an older version to `0.34-alpine` (tried about a month ago) or `0.34.60-alpine` (tried today).
2. Try to load a page with some CubeJS queries that worked before the update, observe the error in the logs.

**Expected behavior**
`alpine` images do not cause errors on startup. Note that using `0.34` works properly, but that image has a lot more vulnerabilities than `alpine`, so we would rather not use it.

**Version:**
0.34

**Comment by ovr** [comment]
Hello @anna-poz ,

As far as I know, all `alpine` images were deprecated. The biggest problem is that Alpine uses MUSL as a standard C library, which makes it annoying to support.

I belive we should remove it.

cC @igorlukanin @paveltiunov 

Thanks

**Comment by anna-poz** [comment]
I see, thank you. If you have a link to the deprecation announcement, or if there is a way those images could be marked as deprecated on dockerhub (e.g. https://hub.docker.com/layers/cubejs/cube/v0.34.60-alpine/images/sha256-6703cb95e344060ef8140b8a4e77cbccafbd7c564d8847c226274435ddb68056?context=explore), that would be very helpful.

What is the image recommended by the Cube team then?

**Comment by igorlukanin** [comment]
Hi @anna-poz, I hope this works as a deprecation announcement: https://cube.dev/blog/cube-core-v0-35-updates-to-data-modeling-and-data-sources#alpine-based-docker-images-removed
