### ISSUE TITLE
AWS S3 error in Cubestore after upgrading to 0.35

### ISSUE THREAD

**Issue by danielli-ziprecruiter** [cube-js/cube#8218]
**Problem**

After upgrading to 0.35, Cubestore is failing at startup with:

```
thread 'main' panicked at /cubestore/cubestore/src/config/mod.rs:1971:34:
called `Result::unwrap()` on an `Err` value: CubeError { message: "AWS S3 error: serde xml: custom: missing field `Name`", backtrace: "", cause: Internal }
stack backtrace:
   0: rust_begin_unwind
             at /rustc/190f4c96116a3b59b7de4881cfec544be0246d84/library/std/src/panicking.rs:647:5
   1: core::panicking::panic_fmt
             at /rustc/190f4c96116a3b59b7de4881cfec544be0246d84/library/core/src/panicking.rs:72:14
   2: core::result::unwrap_failed
             at /rustc/190f4c96116a3b59b7de4881cfec544be0246d84/library/core/src/result.rs:1649:5
   3: cubestore::config::injection::Injector::register_typed::{{closure}}::{{closure}}::{{closure}}
   4: cubestore::config::injection::Injector::get_service_typed::{{closure}}
   5: cubestore::config::injection::Injector::register_typed::{{closure}}::{{closure}}::{{closure}}
   6: cubestore::config::injection::Injector::get_service_typed::{{closure}}
   7: cubestore::config::injection::Injector::register_typed::{{closure}}::{{closure}}::{{closure}}
   8: cubestore::config::injection::Injector::get_service_typed::{{closure}}
   9: cubestored::main::{{closure}}
  10: tokio::runtime::park::CachedParkThread::block_on
  11: tokio::runtime::runtime::Runtime::block_on
  12: cubestored::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
I'm using an S3 export bucket. I also have CUBESTORE_AWS_ACCESS_KEY_ID and CUBESTORE_AWS_SECRET_ACCESS_KEY set to dummy values since I'm not actually using these for auth.

**Comment by danielli-ziprecruiter** [comment]
Closing since issue is already mentioned here.
https://github.com/cube-js/cube/issues/8163#issuecomment-2077396879

**Comment by jlloyd-widen** [comment]
I'm experiencing this same issue.

I think this should be re-opened as per [this comment](https://github.com/cube-js/cube/issues/8163#issuecomment-2173007957); it appears to be different from the original issue #8163.  #8163 could then probably be re-closed.
