### ISSUE TITLE
`One or more Primary key is required for '${cubeName}' cube` error

### ISSUE THREAD

**Issue by Anger79** [cube-js/cube#8351]
**Describe the bug**
Since the last cubejs version update (0.33.53 -> 0.35.41) we started having a query that fails with `"One or more Primary key is required for 'TestCube' cube"` error. 
Query has `"ungrouped": true`.
Cube doesn't have a `primary key`, `pre-aggregations` or `joins`.
`allowUngroupedWithoutPrimaryKey` is set to `true`.

**Query example**
```
{
   "dimensions":[
      "TestCube.device_name",
      "TestCube.device_user",
      "TestCube.timestamp"
   ],
   "timeDimensions":[
      {
         "dimension":"TestCube.timestamp",
         "dateRange":[
            "2024-05-15T01:00:00.000",
            "2024-05-22T01:00:00.000"
         ]
      }
   ],
  "ungrouped": true,
  "offset": 0,
  "limit": 1000
}
```

**Minimally reproducible Cube Schema**
Simple cube without pre-aggregations or joins:
```
cube (`TestCube`, {
    sql: `select * from test_table WHERE ${SECURITY_CONTEXT.account_id.filter('account_id')}`,
    dimensions: {
        device_name: {
            sql: `device_name`,
            type: `string`
        },
        user: {
            sql: `user`,
            type: `string`
        },
        timestamp: {
            sql: `timestamp`,
            type: `time`
        }
    }
})
```

**Version:**
[0.35.41]

**Comment by igorlukanin** [comment]
I was able to reproduce this with v0.35.47. 

The stack trace is the following:
```
Error: One or more Primary key is required for 'TestCube' cube
at PostgresQuery.primaryKeyNames (/node_modules/@cubejs-backend/schema-compiler/src/adapter/BaseQuery.js:2305:13)
at /node_modules/@cubejs-backend/schema-compiler/src/adapter/PreAggregations.js:325:73
at Array.flatMap (<anonymous>)
at Function.transformQueryToCanUseForm (/node_modules/@cubejs-backend/schema-compiler/src/adapter/PreAggregations.js:325:54)
at PreAggregations.canUsePreAggregationFn (/node_modules/@cubejs-backend/schema-compiler/src/adapter/PreAggregations.js:495:23)
at PreAggregations.rollupMatchResults (/node_modules/@cubejs-backend/schema-compiler/src/adapter/PreAggregations.js:828:39)
at PreAggregations.findPreAggregationForQuery (/node_modules/@cubejs-backend/schema-compiler/src/adapter/PreAggregations.js:783:12)
at PostgresQuery.externalPreAggregationQuery (/node_modules/@cubejs-backend/schema-compiler/src/adapter/BaseQuery.js:570:59)
at /node_modules/@cubejs-backend/server-core/src/core/CompilerApi.js:152:30
at DataSchemaCompiler.withQuery (/node_modules/@cubejs-backend/schema-compiler/src/compiler/DataSchemaCompiler.js:176:14)
at getSqlFn (/node_modules/@cubejs-backend/server-core/src/core/CompilerApi.js:151:47)
at QueryCache.cache (/node_modules/@cubejs-backend/schema-compiler/src/adapter/QueryCache.js:22:28)
at CloudCompilerApi.getSql (/node_modules/@cubejs-backend/server-core/src/core/CompilerApi.js:171:57)
at processTicksAndRejections (node:internal/process/task_queues:95:5)
at /node_modules/@cubejs-backend/api-gateway/src/gateway.ts:1463:28
at async Promise.all (index 0)
at CloudApiGateway.getSqlQueriesInternal (/node_modules/@cubejs-backend/api-gateway/src/gateway.ts:1459:24)
at CloudApiGateway.load (/node_modules/@cubejs-backend/api-gateway/src/gateway.ts:1685:26)
at /node_modules/@cubejs-backend/api-gateway/src/gateway.ts:278:7
```

These lines look especially suspicios to me:
```
at PreAggregations.findPreAggregationForQuery (/node_modules/@cubejs-backend/schema-compiler/src/adapter/PreAggregations.js:783:12)
at PostgresQuery.externalPreAggregationQuery (/node_modules/@cubejs-backend/schema-compiler/src/adapter/BaseQuery.js:570:59)
```

It looks like this query is identified as one that would be run using a pre-aggregation (thus requiring a primary key since it's an ungrouped one) but there are no suitable pre-aggregations in fact. I wonder what @paveltiunov or @ovr think about this.

@Anger79 Do you absolutely need to run an `ungrouped` query? As a workaround, you might remove `ungrouped` for now—or downgrade Cube to the previous version.

**Comment by chrisndodge** [comment]
Hello @igorlukanin is there a plan to fix this? I am encountering the same problem. Thank you.

**Comment by igorlukanin** [comment]
Hi @chrisndodge @Anger79 I've talked to the team and it looks like this is an intended behavior for ungrouped queries. If you'd like to run an ungrouped query, please add and reference a primary key.

**Comment by chrisndodge** [comment]
@igorlukanin thank you for the follow up response.
