### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by itestyoy** [cube-js/cube#8707]
After updating from v.0.35.78 to v.0.36.0, we started getting errors like this:

It is probably somehow related to FILTER_PARAMS.

```
cube  | RangeError: Maximum call stack size exceeded

cube  |     at CubeEvaluator.resolveSymbol (/cube/node_modules/@cubejs-backend/schema-compiler/src/compiler/CubeSymbols.js:506:43)
cube  |     at /cube/node_modules/@cubejs-backend/schema-compiler/src/adapter/BaseQuery.js:2357:23
cube  |     at /cube/node_modules/@cubejs-backend/schema-compiler/src/compiler/CubeSymbols.js:455:71
cube  |     at Array.map (<anonymous>)
cube  |     at CubeEvaluator.resolveSymbolsCall (/cube/node_modules/@cubejs-backend/schema-compiler/src/compiler/CubeSymbols.js:455:59)
cube  |     at BigqueryQuery.evaluateSql (/cube/node_modules/@cubejs-backend/schema-compiler/src/adapter/BaseQuery.js:2354:26)
cube  |     at BigqueryQuery.evaluateSymbolSql (/cube/node_modules/@cubejs-backend/schema-compiler/src/adapter/BaseQuery.js:2248:36)
cube  |     at BigqueryQuery.traverseSymbol (/cube/node_modules/@cubejs-backend/schema-compiler/src/adapter/BaseQuery.js:1851:35)
cube  |     at /cube/node_modules/@cubejs-backend/schema-compiler/src/adapter/BaseQuery.js:1902:31
cube  |     at BigqueryQuery.evaluateSymbolSqlWithContext (/cube/node_modules/@cubejs-backend/schema-compiler/src/adapter/BaseQuery.js:2468:22)
cube  |     at BigqueryQuery.collectMemberNamesFor (/cube/node_modules/@cubejs-backend/schema-compiler/src/adapter/BaseQuery.js:2418:10)
cube  |     at /cube/node_modules/@cubejs-backend/schema-compiler/src/adapter/BaseQuery.js:1902:17
cube  |     at CompilerCache.cache (/cube/node_modules/@cubejs-backend/schema-compiler/src/adapter/QueryCache.js:22:28)
cube  |     at /cube/node_modules/@cubejs-backend/schema-compiler/src/adapter/BaseQuery.js:1898:39
cube  |     at _map (/cube/node_modules/@cubejs-backend/schema-compiler/node_modules/ramda/src/internal/_map.js:7:19)
cube  |     at map (/cube/node_modules/@cubejs-backend/schema-compiler/node_modules/ramda/src/map.js:83:14)
cube  |     at /cube/node_modules/@cubejs-backend/schema-compiler/node_modules/ramda/src/internal/_dispatchable.js:50:15
cube  |     at /cube/node_modules/@cubejs-backend/schema-compiler/node_modules/ramda/src/internal/_curry2.js:26:18
cube  |     at f1 (/cube/node_modules/@cubejs-backend/schema-compiler/node_modules/ramda/src/internal/_curry1.js:19:17)
cube  |     at /cube/node_modules/@cubejs-backend/schema-compiler/node_modules/ramda/src/internal/_pipe.js:3:14
cube  |     at /cube/node_modules/@cubejs-backend/schema-compiler/node_modules/ramda/src/internal/_pipe.js:3:27
cube  |     at /cube/node_modules/@cubejs-backend/schema-compiler/node_modules/ramda/src/internal/_pipe.js:3:27
```

**Comment by paveltiunov** [comment]
@itestyoy Could you please share your data model?

**Comment by itestyoy** [comment]
Hi @paveltiunov!

This is not a real use case, it's only for demonstration. Our use case of using FILTER_PARAMS in dimensions involves working with arrays with adding pseudo-columns like is_day_used.

First version with this error v0.35.80.

We really hope that you fix it because this use case is essential for us, and Cube doesn't provide any other options to work with arrays.


```
cube('model', {
    public: false,
    title: 'model',
    sql: `select 1 as metric, 1 as day`,

    dimensions: {
        is_day_used: {
            type: `boolean`,
            sql: `(true)`,
        },

        day: {
            sql: `day`,
            type: 'number'
        },

        test: {
            sql: `(${FILTER_PARAMS.model[`is_day_used`].filter(x => `day = 1`)})`,
            type: `boolean`,
        }
    },

    measures: {
        metric: {
            sql: `metric`,
            type: `sum`
        }
    },
});
```

**Comment by itestyoy** [comment]
Hi! @paveltiunov Is there any update?

**Comment by sabinevidal** [comment]
Hi there @paveltiunov , 
Also jumping on this with the same issue!
model:
```
cube(`report`, {
  sql_table: `"REPORT"`,

  measures: {
    kpiXAvg: {
      sql: `VALUE`,
      type: `avg`,
      filters: [
        { sql: `${CUBE}.KPI = ${FILTER_PARAMS.report.kpiX.filter((kpiX) => kpiX)}` }
      ],
      title: `KPI X Avg`
    },
    kpiYAvg: {
      sql: `VALUE`,
      type: `avg`,
      filters: [
        { sql: `${CUBE}.KPI = ${FILTER_PARAMS.report.kpiY.filter((kpiY) => kpiY)}` }
      ],
      title: `KPI Y Avg`
    }
  },

  dimensions: {
    assetId: {
      sql: `ASSET_ID`,
      type: `string`,
      primary_key: true
    },
    kpi: {
      sql: `KPI`,
      type: `string`
    },
    value: {
      sql: `VALUE`,
      type: `number`
    }
  },
});
```

Error:
```
RangeError: Maximum call stack size exceeded
    at String.replace (<anonymous>)
    at Object.underscore (/cube/node_modules/inflection/lib/inflection.js:802:39)
    at SnowflakeQuery.aliasName (/cube/node_modules/@cubejs-backend/schema-compiler/src/adapter/BaseQuery.js:2863:23)
    at SnowflakeQuery.cubeAlias (/cube/node_modules/@cubejs-backend/schema-compiler/src/adapter/BaseQuery.js:2422:12)
    at cubeAliasFn.withSymbolsCallContext (/cube/node_modules/@cubejs-backend/schema-compiler/src/compiler/CubeSymbols.js:687:21)
    at CubeEvaluator.withSymbolsCallContext (/cube/node_modules/@cubejs-backend/schema-compiler/src/compiler/CubeSymbols.js:503:14)
    at Proxy.<anonymous> (/cube/node_modules/@cubejs-backend/schema-compiler/src/compiler/CubeSymbols.js:686:40)
    at sql (cubes/report_dc_measurement_daily_scatter.js:16:39)
    at CubeEvaluator.resolveSymbolsCall (/cube/node_modules/@cubejs-backend/schema-compiler/src/compiler/CubeSymbols.js:489:22)
    at SnowflakeQuery.evaluateSql (/cube/node_modules/@cubejs-backend/schema-compiler/src/adapter/BaseQuery.js:2388:26)
    at /cube/node_modules/@cubejs-backend/schema-compiler/src/adapter/BaseQuery.js:2719:39
    at Array.map (<anonymous>)
    at SnowflakeQuery.evaluateFiltersArray (/cube/node_modules/@cubejs-backend/schema-compiler/src/adapter/BaseQuery.js:2719:25)
    at SnowflakeQuery.evaluateMeasureFilters (/cube/node_modules/@cubejs-backend/schema-compiler/src/adapter/BaseQuery.js:2715:17)
    at SnowflakeQuery.applyMeasureFilters (/cube/node_modules/@cubejs-backend/schema-compiler/src/adapter/BaseQuery.js:2709:24)
    at SnowflakeQuery.evaluateSymbolSql (/cube/node_modules/@cubejs-backend/schema-compiler/src/adapter/BaseQuery.js:2281:23)
    at SnowflakeQuery.traverseSymbol (/cube/node_modules/@cubejs-backend/schema-compiler/src/adapter/BaseQuery.js:1867:35)
    at /cube/node_modules/@cubejs-backend/schema-compiler/src/adapter/BaseQuery.js:1918:31
    at SnowflakeQuery.evaluateSymbolSqlWithContext (/cube/node_modules/@cubejs-backend/schema-compiler/src/adapter/BaseQuery.js:2501:22)
    at SnowflakeQuery.collectMemberNamesFor (/cube/node_modules/@cubejs-backend/schema-compiler/src/adapter/BaseQuery.js:2451:10)
    at /cube/node_modules/@cubejs-backend/schema-compiler/src/adapter/BaseQuery.js:1918:17
    at CompilerCache.cache (/cube/node_modules/@cubejs-backend/schema-compiler/src/adapter/QueryCache.js:22:28)
```

**Comment by igorlukanin** [comment]
Hey everyone, could you please try with the latest release?

**Comment by raghuveer-s** [comment]
I had the same issue. Tried it with the latest one (v1.1.5) and it works. Thanks!
