### ISSUE TITLE
Cubestore - thread 'main' panicked

### ISSUE THREAD

**Issue by pauldheinrichs** [cube-js/cube#8834]
**Describe the bug**
Recently after updating to 1.0.0 (from v0.36.7) - we started seeing these errors popping up when running cube in development mode on a single container instance. Cube is unable to recover unless you force kill the container to respin up the processes. 

```
devlogs  cube: thread 'main' panicked at /__w/cube/cube/rust/cubestore/cubestore/src/config/mod.rs:1985:34:
dev:logs  cube: called `Result::unwrap()` on an `Err` value: CubeError { message: "DB::open error for metastore: IO error: While lock file: /cube/conf/.cubestore/data/metastore/LOCK: Resource temporarily unavailable", backtrace: "", cause: Internal }
devlogs  cube: stack backtrace:
dev:logs  cube:    0: rust_begin_unwind
dev:logs  cube:              at /rustc/635124704849eeead4e3a7bb6e663c5351571d93/library/std/src/panicking.rs:647:5
dev:logs  cube:    1: core::panicking::panic_fmt
dev:logs  cube:              at /rustc/635124704849eeead4e3a7bb6e663c5351571d93/library/core/src/panicking.rs:72:14
dev:logs  cube:    2: core::result::unwrap_failed
dev:logs  cube:              at /rustc/635124704849eeead4e3a7bb6e663c5351571d93/library/core/src/result.rs:1649:5
dev:logs  cube:    3: cubestore::config::injection::Injector::register_typed::{{closure}}::{{closure}}::{{closure}}
dev:logs  cube:    4: cubestore::config::injection::Injector::get_service_typed::{{closure}}
dev:logs  cube:    5: cubestore::config::injection::Injector::register_typed::{{closure}}::{{closure}}::{{closure}}
dev:logs  cube:    6: cubestore::config::injection::Injector::get_service_typed::{{closure}}
dev:logs  cube:    7: cubestore::config::Config::configure_common::{{closure}}::{{closure}}
dev:logs  cube:    8: cubestore::config::injection::Injector::register_typed::{{closure}}::{{closure}}::{{closure}}
dev:logs  cube:    9: cubestore::config::injection::Injector::get_service_typed::{{closure}}
dev:logs  cube:   10: cubestored::main::{{closure}}
dev:logs  cube:   11: tokio::runtime::park::CachedParkThread::block_on
dev:logs  cube:   12: tokio::runtime::runtime::Runtime::block_on
dev:logs  cube: 13: cubestored::main
```

**Comment by igorlukanin** [comment]
Hi @pauldheinrichs 👋 

I feel like more details would be helpful here. What is your platform/OS version/etc.

Also, can you confirm that if. you switch to v0.36.7 for a day, without changing anything else, this error does not appear?
