### ISSUE TITLE
Feedback for “REST API reference”

### ISSUE THREAD

**Issue by lawrencechong** [cube-js/cube#8893]
Following Instructions to trigger `v1/pre-aggregations/jobs` to `Retrieving statuses of jobs` returns this error

curl \
  -d '{
    "action": "get",
  }' \
  -H "Content-Type: application/json" \
  -X GET \
  http://mycubejs.com:4000/cubejs-api/v1/pre-aggregations/jobs

{"error":"SyntaxError: Expected double-quoted property name in JSON at position 25","stack":"SyntaxError: Expected double-quoted property name in JSON at position 25\n    at JSON.parse (<anonymous>)\n    at parse (/cube/node_modules/body-parser/lib/types/json.js:92:19)\n    at /cube/node_modules/body-parser/lib/read.js:128:18\n    at AsyncResource.runInAsyncScope (node:async_hooks:206:9)\n    at invokeCallback (/cube/node_modules/raw-body/index.js:238:16)\n    at done (/cube/node_modules/raw-body/index.js:227:7)\n    at IncomingMessage.onEnd (/cube/node_modules/raw-body/index.js:287:7)\n    at IncomingMessage.emit (node:events:519:28)\n    at endReadableNT (node:internal/streams/readable:1696:12)\n    at processTicksAndRejections (node:internal/process/task_queues:82:21)"}%    

Details
- self hosted
- updated configs to include `jobs` scope
- our system has 1 cubestore router and 3 cubestore workers
- running in dev mode without auth

**Comment by igorlukanin** [comment]
Hi @lawrencechong 👋 

I believe this is not a correct request. The `tokens` parameter is required for the `get` action. Please see the example in the docs: https://cube.dev/docs/reference/rest-api#retrieving-statuses-of-jobs

**Comment by lawrencechong** [comment]
@igorlukanin is there anyway to have tokens be optional and have it return all jobs?

**Comment by igorlukanin** [comment]
This is not what is currently implemented but I guess this might be a nice feature request.
